package Bill;

import Data_base_Conection.DataBase_connection;
import Login.Main_page;
import static Login.Main_page.con;
import Products.View_product;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class All_Bill_Records extends javax.swing.JInternalFrame {

    
   
    public All_Bill_Records() throws SQLException {
        initComponents();
       //grt_All_bills_by_amount();
        
        
    }
    
    public void grt_All_bills_by_amount() throws SQLException
    {
        PreparedStatement ps =null;
        ResultSet rs=null;
        String Query="select * from Bill_Amount";
        ps=Main_page.con.prepareStatement(Query);
        rs=ps.executeQuery();
        
        ResultSetMetaData resmetadata =  rs.getMetaData();
        int coulumb = resmetadata.getColumnCount();
        DefaultTableModel bill_list = new  DefaultTableModel();
        Vector culomb_name = new Vector();
        Vector dataros= new Vector();
        
        for(int i = 1 ; i <= coulumb; i++)
        {
            culomb_name.addElement(resmetadata.getColumnName(i));
            
            
        }
       bill_list.setColumnIdentifiers(culomb_name);
    
        while(rs.next())
        {
            dataros= new Vector();
            for(int j = 1 ; j <=coulumb ; j++)
            {
                dataros.addElement(rs.getString(j));
                
            }
            bill_list.addRow(dataros);
        }
        jTable1.setModel(bill_list);
    }

       public void grt_All_bills_by_product_sale() throws SQLException
    {
        PreparedStatement ps =null;
        ResultSet rs=null;
        String Query="select * from Bill_Product order by Bill_ID ";
        ps=Main_page.con.prepareStatement(Query);
        rs=ps.executeQuery();
        
        ResultSetMetaData resmetadata =  rs.getMetaData();
        int coulumb = resmetadata.getColumnCount();
        DefaultTableModel bill_list = new  DefaultTableModel();
        Vector culomb_name = new Vector();
        Vector dataros= new Vector();
        
        for(int i = 1 ; i <= coulumb; i++)
        {
            culomb_name.addElement(resmetadata.getColumnName(i));
            
            
        }
       bill_list.setColumnIdentifiers(culomb_name);
    
        while(rs.next())
        {
            dataros= new Vector();
            for(int j = 1 ; j <=coulumb ; j++)
            {
                dataros.addElement(rs.getString(j));
                
            }
            bill_list.addRow(dataros);
        }
        jTable1.setModel(bill_list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1_view = new javax.swing.JButton();
        jRadioButton1_Bill_amouny = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton_print_brn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("All Bill Records");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("AR BONNIE", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("all Bill Records");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 11, 251, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Bill ID", "Date", "Time", "Customer Name", "Product Name", "Rate", "Quantity", "Total Amount", "Customer Remaining Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 856, 326));

        jButton1_view.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_view.setText("View");
        jButton1_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_viewActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 101, 112, -1));

        buttonGroup1.add(jRadioButton1_Bill_amouny);
        jRadioButton1_Bill_amouny.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1_Bill_amouny.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButton1_Bill_amouny.setText("View by Bill Amounts And Customer Name");
        jRadioButton1_Bill_amouny.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jRadioButton1_Bill_amouny, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 101, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 51, 153));
        jRadioButton1.setText("View by Product Sale");
        jRadioButton1.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 101, 181, -1));

        jButton_print_brn.setBackground(new java.awt.Color(255, 102, 0));
        jButton_print_brn.setText("Print Records");
        jButton_print_brn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_print_brnActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_print_brn, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 510, 113, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bill/beautiful_light_blue_sky-wallpaper-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_viewActionPerformed
      if(jRadioButton1_Bill_amouny.isSelected())
      {
          try {
              grt_All_bills_by_amount();
          } catch (SQLException ex) {
              Logger.getLogger(All_Bill_Records.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
      if(jRadioButton1.isSelected())
      {
          try {
          grt_All_bills_by_product_sale();
          } catch (SQLException ex) {
              Logger.getLogger(All_Bill_Records.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
    }//GEN-LAST:event_jButton1_viewActionPerformed

    private void jButton_print_brnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_print_brnActionPerformed
       if(jRadioButton1_Bill_amouny.isSelected())
       {
           try {
            // C:\Users\Shahyar\Desktop
            //JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Report_practise\\report2.jrxml");
              //String sql =  "select * from account";
              JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Inventory_managment\\Reports\\Bills\\Bill_amount.jrxml");

             String sql =  "select * from Bill_Amount";
            
            
            JRDesignQuery  newquer  = new JRDesignQuery();
             newquer.setText(sql);
            jd.setQuery(newquer);
            JasperReport jr =  JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null , con);
             JasperViewer.viewReport(jp,false);
        } catch (JRException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        } 
       }
       
       
       if(jRadioButton1.isSelected())
       {
            try {
            // C:\Users\Shahyar\Desktop
            //JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Report_practise\\report2.jrxml");
              //String sql =  "select * from account";
              JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Inventory_managment\\Reports\\Bills\\bill_product.jrxml");

             String sql =  "select * from Bill_Product order by Bill_ID ";
            
            
            JRDesignQuery  newquer  = new JRDesignQuery();
             newquer.setText(sql);
            jd.setQuery(newquer);
            JasperReport jr =  JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null , con);
             JasperViewer.viewReport(jp,false);
        } catch (JRException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        } 
       }
        
       
    }//GEN-LAST:event_jButton_print_brnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1_view;
    private javax.swing.JButton jButton_print_brn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton1_Bill_amouny;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
