package Bill;


import Bill.New_bill;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class  Conformation_bill extends javax.swing.JInternalFrame {

    /**
     * Creates new form Conformation_bill
     */
    public Conformation_bill() {
        initComponents();
        
//        int customer_balance;
//        int total_bill_amount;
//        int customer_remaining_balance;
//        customer_balance =Integer.parseInt(New_bill.jLabel_customer_balance_show.getText());
//        total_bill_amount = Integer.parseInt(New_bill.jLabel_total_bill_amount_show.getText());
//        customer_remaining_balance = customer_balance - total_bill_amount;
//        
//        jLabel_customer_name_show.setText(New_bill.jLabel_customer_name_shpw.getText());
//        jLabel_product_name_show.setText(New_bill.jLabel_product_name_show.getText());
//        jLabel_product_qnt_show.setText(New_bill.jTextField_puchase_quantity.getText());
//        jLabel_product_rate_show.setText(New_bill.jLabel_product_rate_show.getText());
//        jLabel_total_amnt_show.setText(New_bill.jLabel_total_bill_amount_show.getText());
//        jLabel_date_show.setText(New_bill.jLabel_date_show.getText());
//        jLabel_time_show.setText(New_bill.jLabel_time_show.getText());
//        jLabel8_bill_id_show.setText(New_bill.jLabel_bill_id_show.getText());
//        jLabel_custom_r_b_show.setText(String.valueOf(customer_remaining_balance));
//    }

    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_customer_name = new javax.swing.JLabel();
        jLabel_product_name = new javax.swing.JLabel();
        jLabel_product_qnt = new javax.swing.JLabel();
        jLabel_product_rate = new javax.swing.JLabel();
        jLabel_total_amnt = new javax.swing.JLabel();
        jLabel_custom_r_b = new javax.swing.JLabel();
        jLabel8_bill_id_show = new javax.swing.JLabel();
        jLabel_customer_name_show = new javax.swing.JLabel();
        jLabel_product_name_show = new javax.swing.JLabel();
        jLabel_product_qnt_show = new javax.swing.JLabel();
        jLabel_product_rate_show = new javax.swing.JLabel();
        jLabel_total_amnt_show = new javax.swing.JLabel();
        jLabel_custom_r_b_show = new javax.swing.JLabel();
        jButton1_save_bill = new javax.swing.JButton();
        jButton_Close = new javax.swing.JButton();
        Bill_status_show = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_date_show = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_time_show = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Bill Conformation");

        jLabel1.setText("Bill ID :");

        jLabel_customer_name.setText("Customer Name .........................");

        jLabel_product_name.setText("Product Name.........................");

        jLabel_product_qnt.setText("Product Quantity......................");

        jLabel_product_rate.setText("Product Rate..........................");

        jLabel_total_amnt.setText("Total Amount...........................");

        jLabel_custom_r_b.setText("Remaining Balance....................");

        jLabel8_bill_id_show.setText("jLabel8");

        jLabel_customer_name_show.setText("Customer name");

        jLabel_product_name_show.setText("Product name");

        jLabel_product_qnt_show.setText("Quantity");

        jLabel_product_rate_show.setText("rate");

        jLabel_total_amnt_show.setText("total");

        jLabel_custom_r_b_show.setText("balance'");

        jButton1_save_bill.setText("Save Bill");
        jButton1_save_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_save_billActionPerformed(evt);
            }
        });

        jButton_Close.setText("Close");
        jButton_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bill_status_show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1_save_bill)
                        .addGap(34, 34, 34)
                        .addComponent(jButton_Close))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8_bill_id_show))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_customer_name_show))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_product_name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_product_qnt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_product_qnt_show)
                            .addComponent(jLabel_product_name_show)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel_product_rate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_custom_r_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_total_amnt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel_custom_r_b_show))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_product_rate_show))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_total_amnt_show)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8_bill_id_show))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_customer_name)
                    .addComponent(jLabel_customer_name_show))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_product_name)
                    .addComponent(jLabel_product_name_show))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_product_qnt)
                    .addComponent(jLabel_product_qnt_show))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_product_rate)
                    .addComponent(jLabel_product_rate_show))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_total_amnt)
                    .addComponent(jLabel_total_amnt_show))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_custom_r_b)
                    .addComponent(jLabel_custom_r_b_show))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_save_bill)
                    .addComponent(jButton_Close))
                .addGap(18, 18, 18)
                .addComponent(Bill_status_show, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel10.setText("Date :");

        jLabel_date_show.setText("jLabel11");

        jLabel12.setText("Time :");

        jLabel_time_show.setText("jLabel13");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_date_show)
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_time_show)
                .addGap(0, 205, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel_date_show)
                    .addComponent(jLabel12)
                    .addComponent(jLabel_time_show)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CloseActionPerformed
      
        this.setVisible(false);
    }//GEN-LAST:event_jButton_CloseActionPerformed

    private void jButton1_save_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_save_billActionPerformed
        Conform_bill_bal ob = new Conform_bill_bal();
        int bill_id = Integer.parseInt(jLabel8_bill_id_show.getText());
        String date =jLabel_date_show.getText();
        String time = jLabel_time_show.getText();
        String cus_name = jLabel_customer_name_show.getText();
        String pro_name = jLabel_product_name_show.getText();
        int rate = Integer.parseInt(jLabel_product_rate_show.getText());
        int qnt =  Integer.parseInt(jLabel_product_qnt_show.getText());
        int total = Integer.parseInt(jLabel_total_amnt_show.getText());
        int r_b_cus = Integer.parseInt(jLabel_custom_r_b_show.getText());
         int status;       
        try {
           status =  ob.save_Bill(bill_id, date, time, cus_name, pro_name, rate, qnt, total, r_b_cus);
                    if(status != 0)
                    {
                     Bill_status_show.setText("Bill Is Saved Succesfully");
                    }
                    else
                    {
                        Bill_status_show.setText("Bill Not Save");
                    }
                    } catch (SQLException ex) {
            Logger.getLogger(Conformation_bill.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            ob.update_customer_balnce(cus_name, r_b_cus);
        } catch (SQLException ex) {
            Logger.getLogger(Conformation_bill.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            ob.minus_quantity_afterBill(pro_name, qnt);
        } catch (SQLException ex) {
            Logger.getLogger(Conformation_bill.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1_save_billActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bill_status_show;
    private javax.swing.JButton jButton1_save_bill;
    private javax.swing.JButton jButton_Close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8_bill_id_show;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_custom_r_b;
    private javax.swing.JLabel jLabel_custom_r_b_show;
    private javax.swing.JLabel jLabel_customer_name;
    private javax.swing.JLabel jLabel_customer_name_show;
    private javax.swing.JLabel jLabel_date_show;
    private javax.swing.JLabel jLabel_product_name;
    private javax.swing.JLabel jLabel_product_name_show;
    private javax.swing.JLabel jLabel_product_qnt;
    private javax.swing.JLabel jLabel_product_qnt_show;
    private javax.swing.JLabel jLabel_product_rate;
    private javax.swing.JLabel jLabel_product_rate_show;
    private javax.swing.JLabel jLabel_time_show;
    private javax.swing.JLabel jLabel_total_amnt;
    private javax.swing.JLabel jLabel_total_amnt_show;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
