/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import static Login.Main_page.jMenuItem6_log_out;
import java.awt.Color;
import java.awt.Toolkit;
import java.security.CryptoPrimitive;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Shahyar
 */
public class Login_window extends javax.swing.JInternalFrame {

    /**
     * Creates new form Login_window
     */
    public Login_window() throws InterruptedException {
         
        initComponents();
       
                   Main_page.jMenu1_main_customer.setEnabled(false);
                   Main_page.jMenu7_main_product.setEnabled(false);
                   Main_page.jMenu8_file.setEnabled(true);
                   Main_page.jMenu1_bill_search.setEnabled(false);
                   Main_page.jMenu6_bill.setEnabled(false);
                   Main_page.jMenu1_Account.setEnabled(false);
                   Main_page.jMenuItem7_add_new_accnt.setEnabled(false);
                   Main_page.jMenuItem7_change_pass.setEnabled(false);
                   jPasswordField_password.setBackground(Color.white);
        
    }
                    public static String Current_User_Name;
                    public static String Current_User_Password;
                    public static int Current_user_Type;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2_close = new javax.swing.JButton();
        jLabel1_status = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3_lock_image = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Log In");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Select Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 68, 30));

        jButton2_close.setBackground(new java.awt.Color(51, 51, 255));
        jButton2_close.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton2_close.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_close.setText("Close");
        jButton2_close.setToolTipText("Close");
        jButton2_close.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_close.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/login_user_profile_account-512.png"))); // NOI18N
        jButton2_close.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/login_user_profile_account-512.png"))); // NOI18N
        jButton2_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_closeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 110, 60));

        jLabel1_status.setFont(new java.awt.Font("AR BONNIE", 1, 26)); // NOI18N
        jLabel1_status.setForeground(new java.awt.Color(104, 104, 232));
        getContentPane().add(jLabel1_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 210, 70));

        user_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        user_name.setToolTipText("Enter User Name");
        user_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        user_name.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        user_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_nameFocusGained(evt);
            }
        });
        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 232, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 10, 170));

        jPasswordField_password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPasswordField_password.setToolTipText("Enter Password");
        jPasswordField_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jPasswordField_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_passwordFocusGained(evt);
            }
        });
        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 232, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log in");
        jButton1.setToolTipText("Log in");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 93, 110, 60));

        jLabel1.setFont(new java.awt.Font("AR BONNIE", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 104, 232));
        jLabel1.setText("Login Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 270, 60));

        jLabel3_lock_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Lock_images/1.png"))); // NOI18N
        getContentPane().add(jLabel3_lock_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 170, 140));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/log_in_backGroundl.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String checl_name = user_name.getText();
String check_pass = jPasswordField_password.getText();
      

        textfield_bal ob = new textfield_bal();
        boolean s;
            if(check_pass.equalsIgnoreCase("") || checl_name.equalsIgnoreCase(""))
            {
                if(check_pass.equalsIgnoreCase(""))
                {
                    jPasswordField_password.setBackground(Color.RED);
                    
                }
                
                if(checl_name.equalsIgnoreCase(""))
                {
                    
                    user_name.setBackground(Color.RED);
                    
                }
            }
            else
            {
        if(jComboBox1.getSelectedIndex() == 0)
        {
            try {
                s= ob.login_check_Admin(user_name.getText(), jPasswordField_password.getText());
                if(s == true)
                {
                   jLabel1_status.setText("Login Succesfull");
                   Main_page.jMenu1_main_customer.setEnabled(true);
                   Main_page.jMenu7_main_product.setEnabled(true);
                   Main_page.jMenu8_file.setEnabled(true);
                   Main_page.jMenu1_bill_search.setEnabled(true);
                   Main_page.jMenu6_bill.setEnabled(true);
                   Main_page.jMenuItem6_log_out.setEnabled(true);
                   Main_page.jMenuItem7_log_in.setEnabled(false);
                   Main_page.jMenu1_Account.setEnabled(true);
                   Main_page.jMenuItem7_add_new_accnt.setEnabled(true);
                   Main_page.jMenuItem7_change_pass.setEnabled(true);
                   Main_page.jLabel1_status_user.setText("ADMIN MODE");
                   Main_page.jLabel1_name.setText("NAME : ");
                    Current_User_Name = user_name.getText();
                    Main_page.jLabel2_user_name_show.setText(Current_User_Name);
                    
                    
                    Current_User_Password = jPasswordField_password.getText();
                    Current_user_Type = jComboBox1.getSelectedIndex();
                    
                    //ICON IMAGE
                    
                    ImageIcon ic = new ImageIcon(getClass().getResource("/Login/Lock_images/2.png"));
                    jLabel3_lock_image.setIcon(ic);
                    //ICON IMAGE
                    // THREAD
                 //  Toolkit.getDefaultToolkit().beep();
                   // THREAD
                   
//                   this.setVisible(false);
//                     Thread.sleep(5000);
                }
                else
                {
                    jLabel1_status.setText("Login Failed");
                }

            } catch (SQLException ex) {
                Logger.getLogger(textfield.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        if(jComboBox1.getSelectedIndex() == 1)
        {
            try {
                s= ob.login_check_user(user_name.getText(), jPasswordField_password.getText());

                if(s == true)
                {
                    jLabel1_status.setText("Login Succesfull");
                   Main_page.jMenu1_main_customer.setEnabled(false);
                   Main_page.jMenu7_main_product.setEnabled(false);
                   Main_page.jMenu8_file.setEnabled(true);
                   Main_page.jMenu1_bill_search.setEnabled(true);
                   Main_page.jMenu6_bill.setEnabled(true);
                    Main_page.jMenuItem6_log_out.setEnabled(true);
                    Main_page.jMenuItem7_log_in.setEnabled(false);
                    Main_page.jMenu1_Account.setEnabled(true);
                     Main_page.jMenuItem7_change_pass.setEnabled(true);
                     Main_page.jLabel1_status_user.setText("USER MODE");                    
                    Main_page.jLabel1_name.setText("NAME : ");
                   Current_User_Name = user_name.getText();
                   Main_page.jLabel2_user_name_show.setText(Current_User_Name);
                   Current_User_Password = jPasswordField_password.getText();
                   Current_user_Type = jComboBox1.getSelectedIndex();
                   
                      //ICON IMAGE
                    ImageIcon ic_2 = new ImageIcon(getClass().getResource("/Login/Lock_images/2.png"));
                    jLabel3_lock_image.setIcon(ic_2);
                    
                   // Toolkit.getDefaultToolkit().beep();
                    //ICON IMAGE
                   // THREAD
                  
                   // THREAD
                   
                   
                 //  this.setVisible(false);
                    // Thread.sleep(5000);
                }
                else
                {
                    jLabel1_status.setText("Login Failed");
                }

            } catch (SQLException ex) {
                Logger.getLogger(textfield.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
            }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_closeActionPerformed
        Main_page.jMenu1_Account.setEnabled(true);
        
        Main_page.jMenuItem6_log_out.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2_closeActionPerformed

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jPasswordField_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_passwordFocusGained
     jLabel1_status.setText("");
     jPasswordField_password.setBackground(Color.white);
    }//GEN-LAST:event_jPasswordField_passwordFocusGained

    private void user_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_nameFocusGained
        
jLabel1_status.setText("");
user_name.setBackground(Color.white);
// TODO add your handling code here:
    }//GEN-LAST:event_user_nameFocusGained

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2_close;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1_status;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_lock_image;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
