package Login;


import Customer.Update_account;
import Customer.View_Accounts;
import Customer.Delete_customer;
import Bill.Daily_sale;
import Customer.Add_Account;
import Customer.Add_customer_bln;
import Products.Update_product;
import Products.View_product;
import Bill.All_Bill_Records;
import Bill.Bill_search;
import Products.Delete_product;
import Bill.New_bill;
import Data_base_Conection.DataBase_connection;
import Products.Add_qnt_new;
import Products.Add_product;
import java.awt.Color;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Shahyar
 */
public class Main_page extends javax.swing.JFrame {

    /**
     * Creates new form Main_page
     */
      
        public static Connection con;      
        static String connectionUrl = "jdbc:sqlserver://localhost;" 
        +"Database=Uni_Project";
        static String user="sa";
        static String passwd="123";
        static  String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
        public static PreparedStatement ps =null;  
        static ResultSet rs = null;
        
        
    public Main_page() throws InterruptedException {
      initComponents();
     jMenuItem9_Add_product_qnt.setBackground(Color.yellow);
      this.setExtendedState(this.MAXIMIZED_BOTH);
      Dimension size = this.getSize();
      jDesktopPane2.setSize(size.width, size.height);
      jMenu1_main_customer.setEnabled(false);
      jMenu7_main_product.setEnabled(false);
      jMenu8_file.setEnabled(false);
      jMenu1_bill_search.setEnabled(false);
      jMenu6_bill.setEnabled(false);
      jMenuItem6_log_out.setEnabled(false);
      jMenu1_Account.setEnabled(false);
     
        
    
//        Login_window login = new Login_window();
//       jDesktopPane2.add(login);
//       Dimension pareentSize = jDesktopPane2.getSize();
//       Dimension childSize = login.getSize();
//       login.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);    
//       login.show();
//        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel1_status_user = new javax.swing.JLabel();
        jLabel1_name = new javax.swing.JLabel();
        jLabel2_user_name_show = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8_file = new javax.swing.JMenu();
        jMenuItem6_log_out = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7_exit = new javax.swing.JMenuItem();
        jMenu1_Account = new javax.swing.JMenu();
        jMenuItem7_log_in = new javax.swing.JMenuItem();
        jMenuItem7_add_new_accnt = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7_change_pass = new javax.swing.JMenuItem();
        jMenu1_bill_search = new javax.swing.JMenu();
        jMenuItem14_search = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6_bill = new javax.swing.JMenu();
        jMenuItem7_new_bill = new javax.swing.JMenuItem();
        jMenuItem8_view_all_bills = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15_daily_sale = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7_print_bill = new javax.swing.JMenuItem();
        jMenu1_main_customer = new javax.swing.JMenu();
        jMenuItem4_add_customer = new javax.swing.JMenuItem();
        jMenuItem10_add_customer_blnc = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6_view_all_customer = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_update_customer = new javax.swing.JMenuItem();
        jMenuItem13_delet_customer = new javax.swing.JMenuItem();
        jMenu7_main_product = new javax.swing.JMenu();
        jMenuItem3_add_product = new javax.swing.JMenuItem();
        jMenuItem9_Add_product_qnt = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2_view_all_product = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_update_product = new javax.swing.JMenuItem();
        jMenuItem12_dlt_product = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem5.setText("jMenuItem5");

        jMenu2.setText("jMenu2");

        jMenuItem11.setText("jMenuItem11");

        jMenuItem2.setText("jMenuItem2");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenuItem3.setText("jMenuItem3");

        jMenu9.setText("jMenu9");

        jMenu10.setText("jMenu10");

        jMenuItem6.setText("jMenuItem6");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Managment");

        jDesktopPane2.setBackground(new java.awt.Color(0, 102, 102));
        jDesktopPane2.setMaximumSize(new java.awt.Dimension(0, 0));
        jDesktopPane2.setName("Main Page"); // NOI18N
        jDesktopPane2.setRequestFocusEnabled(false);

        jLabel1_status_user.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1_status_user.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1_name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1_name.setForeground(new java.awt.Color(51, 51, 0));

        jLabel2_user_name_show.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2_user_name_show.setForeground(new java.awt.Color(255, 153, 51));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 57)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Welcome to ");
        jLabel2.setFocusTraversalPolicyProvider(true);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 57)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Stock Managment System");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/onScrenLOGO-1.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/wallup-192116.jpg"))); // NOI18N

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(966, 966, 966)
                        .addComponent(jLabel2_user_name_show, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(861, 861, 861)
                        .addComponent(jLabel1_status_user, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(861, 861, 861)
                        .addComponent(jLabel1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2_user_name_show, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1_status_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jDesktopPane2.setLayer(jLabel1_status_user, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel1_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2_user_name_show, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar3.setBackground(new java.awt.Color(0, 153, 153));
        jMenuBar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar3.setForeground(new java.awt.Color(0, 0, 153));
        jMenuBar3.setToolTipText("Menu Bar");
        jMenuBar3.setAutoscrolls(true);
        jMenuBar3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N

        jMenu8_file.setForeground(new java.awt.Color(0, 0, 153));
        jMenu8_file.setText("File");
        jMenu8_file.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu8_file.setIconTextGap(20);

        jMenuItem6_log_out.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6_log_out.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6_log_out.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem6_log_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/logout-icon.png"))); // NOI18N
        jMenuItem6_log_out.setText("Log out");
        jMenuItem6_log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6_log_outActionPerformed(evt);
            }
        });
        jMenu8_file.add(jMenuItem6_log_out);
        jMenu8_file.add(jSeparator6);

        jMenuItem7_exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7_exit.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem7_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/exit.png"))); // NOI18N
        jMenuItem7_exit.setText("Exit");
        jMenuItem7_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_exitActionPerformed(evt);
            }
        });
        jMenu8_file.add(jMenuItem7_exit);

        jMenuBar3.add(jMenu8_file);

        jMenu1_Account.setBackground(new java.awt.Color(0, 204, 204));
        jMenu1_Account.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1_Account.setText("Account");
        jMenu1_Account.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1_Account.setIconTextGap(20);

        jMenuItem7_log_in.setBackground(new java.awt.Color(0, 204, 204));
        jMenuItem7_log_in.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7_log_in.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem7_log_in.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/login.png"))); // NOI18N
        jMenuItem7_log_in.setText("Login in");
        jMenuItem7_log_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_log_inActionPerformed(evt);
            }
        });
        jMenu1_Account.add(jMenuItem7_log_in);

        jMenuItem7_add_new_accnt.setBackground(new java.awt.Color(0, 204, 204));
        jMenuItem7_add_new_accnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7_add_new_accnt.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem7_add_new_accnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/sign_up.png"))); // NOI18N
        jMenuItem7_add_new_accnt.setText("Add New Account");
        jMenuItem7_add_new_accnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_add_new_accntActionPerformed(evt);
            }
        });
        jMenu1_Account.add(jMenuItem7_add_new_accnt);
        jMenu1_Account.add(jSeparator7);

        jMenuItem7_change_pass.setBackground(new java.awt.Color(0, 204, 204));
        jMenuItem7_change_pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7_change_pass.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem7_change_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/change_pass.png"))); // NOI18N
        jMenuItem7_change_pass.setText("Change Password");
        jMenuItem7_change_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_change_passActionPerformed(evt);
            }
        });
        jMenu1_Account.add(jMenuItem7_change_pass);

        jMenuBar3.add(jMenu1_Account);

        jMenu1_bill_search.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1_bill_search.setText("Bill Search");
        jMenu1_bill_search.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1_bill_search.setIconTextGap(20);

        jMenuItem14_search.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem14_search.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem14_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/search_bill.png"))); // NOI18N
        jMenuItem14_search.setText("Search");
        jMenuItem14_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14_searchActionPerformed(evt);
            }
        });
        jMenu1_bill_search.add(jMenuItem14_search);

        jMenuBar3.add(jMenu1_bill_search);

        jMenu11.setForeground(new java.awt.Color(0, 0, 153));
        jMenu11.setText("Practise");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu11.setIconTextGap(20);
        jMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu11ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("jMenuItem4");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem4);

        jMenuBar3.add(jMenu11);

        jMenu6_bill.setForeground(new java.awt.Color(0, 0, 153));
        jMenu6_bill.setText("Bills");
        jMenu6_bill.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu6_bill.setIconTextGap(20);

        jMenuItem7_new_bill.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7_new_bill.setFont(new java.awt.Font("Segoe WP", 0, 14)); // NOI18N
        jMenuItem7_new_bill.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem7_new_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/new_bill.png"))); // NOI18N
        jMenuItem7_new_bill.setText("New Bill");
        jMenuItem7_new_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_new_billActionPerformed(evt);
            }
        });
        jMenu6_bill.add(jMenuItem7_new_bill);

        jMenuItem8_view_all_bills.setFont(new java.awt.Font("Segoe WP", 0, 14)); // NOI18N
        jMenuItem8_view_all_bills.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem8_view_all_bills.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/view_bills.png"))); // NOI18N
        jMenuItem8_view_all_bills.setText("View All Bill Records");
        jMenuItem8_view_all_bills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_view_all_billsActionPerformed(evt);
            }
        });
        jMenu6_bill.add(jMenuItem8_view_all_bills);
        jMenu6_bill.add(jSeparator5);

        jMenuItem15_daily_sale.setFont(new java.awt.Font("Segoe WP", 0, 14)); // NOI18N
        jMenuItem15_daily_sale.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem15_daily_sale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/daily sales.png"))); // NOI18N
        jMenuItem15_daily_sale.setText("Daily Sale");
        jMenuItem15_daily_sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15_daily_saleActionPerformed(evt);
            }
        });
        jMenu6_bill.add(jMenuItem15_daily_sale);
        jMenu6_bill.add(jSeparator8);

        jMenuItem7_print_bill.setFont(new java.awt.Font("Segoe WP", 0, 14)); // NOI18N
        jMenuItem7_print_bill.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem7_print_bill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/print_bill.png"))); // NOI18N
        jMenuItem7_print_bill.setText("Print Bill");
        jMenuItem7_print_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_print_billActionPerformed(evt);
            }
        });
        jMenu6_bill.add(jMenuItem7_print_bill);

        jMenuBar3.add(jMenu6_bill);

        jMenu1_main_customer.setForeground(new java.awt.Color(0, 0, 153));
        jMenu1_main_customer.setText("Customers");
        jMenu1_main_customer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenu1_main_customer.setIconTextGap(20);

        jMenuItem4_add_customer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4_add_customer.setBackground(new java.awt.Color(0, 51, 255));
        jMenuItem4_add_customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem4_add_customer.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem4_add_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/add_customer.png"))); // NOI18N
        jMenuItem4_add_customer.setText("Add Customer");
        jMenuItem4_add_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_add_customerActionPerformed(evt);
            }
        });
        jMenu1_main_customer.add(jMenuItem4_add_customer);

        jMenuItem10_add_customer_blnc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem10_add_customer_blnc.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem10_add_customer_blnc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/add_blnc.png"))); // NOI18N
        jMenuItem10_add_customer_blnc.setText("Add Customer Balance");
        jMenuItem10_add_customer_blnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10_add_customer_blncActionPerformed(evt);
            }
        });
        jMenu1_main_customer.add(jMenuItem10_add_customer_blnc);
        jMenu1_main_customer.add(jSeparator1);

        jMenuItem6_view_all_customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6_view_all_customer.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem6_view_all_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/view_customer.png"))); // NOI18N
        jMenuItem6_view_all_customer.setText("View All Customer");
        jMenuItem6_view_all_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6_view_all_customerActionPerformed(evt);
            }
        });
        jMenu1_main_customer.add(jMenuItem6_view_all_customer);
        jMenu1_main_customer.add(jSeparator2);

        jMenuItem_update_customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_update_customer.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem_update_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/update_customer.jpeg"))); // NOI18N
        jMenuItem_update_customer.setText("Update Customer");
        jMenuItem_update_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_update_customerActionPerformed(evt);
            }
        });
        jMenu1_main_customer.add(jMenuItem_update_customer);

        jMenuItem13_delet_customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem13_delet_customer.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem13_delet_customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/deletcustomer.png"))); // NOI18N
        jMenuItem13_delet_customer.setText("Delete Customer");
        jMenuItem13_delet_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13_delet_customerActionPerformed(evt);
            }
        });
        jMenu1_main_customer.add(jMenuItem13_delet_customer);

        jMenuBar3.add(jMenu1_main_customer);

        jMenu7_main_product.setForeground(new java.awt.Color(0, 0, 153));
        jMenu7_main_product.setText("Products");
        jMenu7_main_product.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem3_add_product.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3_add_product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3_add_product.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem3_add_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/icon-add-product.png"))); // NOI18N
        jMenuItem3_add_product.setText("Add product");
        jMenuItem3_add_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3_add_productActionPerformed(evt);
            }
        });
        jMenu7_main_product.add(jMenuItem3_add_product);

        jMenuItem9_Add_product_qnt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem9_Add_product_qnt.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem9_Add_product_qnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/product-shipping-icon-42503.png"))); // NOI18N
        jMenuItem9_Add_product_qnt.setText("Add product Quantity");
        jMenuItem9_Add_product_qnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_Add_product_qntActionPerformed(evt);
            }
        });
        jMenu7_main_product.add(jMenuItem9_Add_product_qnt);
        jMenu7_main_product.add(jSeparator3);

        jMenuItem2_view_all_product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2_view_all_product.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem2_view_all_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/view_product.png"))); // NOI18N
        jMenuItem2_view_all_product.setText("View all products");
        jMenuItem2_view_all_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2_view_all_productActionPerformed(evt);
            }
        });
        jMenu7_main_product.add(jMenuItem2_view_all_product);
        jMenu7_main_product.add(jSeparator4);

        jMenuItem_update_product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_update_product.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem_update_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/update.png"))); // NOI18N
        jMenuItem_update_product.setText("Update Product");
        jMenuItem_update_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_update_productActionPerformed(evt);
            }
        });
        jMenu7_main_product.add(jMenuItem_update_product);

        jMenuItem12_dlt_product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem12_dlt_product.setForeground(new java.awt.Color(51, 0, 102));
        jMenuItem12_dlt_product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/remove_event_32.png"))); // NOI18N
        jMenuItem12_dlt_product.setText("Delete Product");
        jMenuItem12_dlt_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12_dlt_productActionPerformed(evt);
            }
        });
        jMenu7_main_product.add(jMenuItem12_dlt_product);

        jMenuBar3.add(jMenu7_main_product);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6_view_all_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6_view_all_customerActionPerformed

        View_Accounts ob = null;
        try {
            ob = new View_Accounts();
        } catch (SQLException ex) {
            Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane2.add(ob);
          Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob.getSize();
       ob.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
       
       
        ob.show();
    }//GEN-LAST:event_jMenuItem6_view_all_customerActionPerformed

    private void jMenuItem2_view_all_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2_view_all_productActionPerformed

        View_product ob = null;
        try {
            ob = new View_product();
        } catch (SQLException ex) {
            Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane2.add(ob);
          Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob.getSize();
       ob.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
       
        ob.show();

    }//GEN-LAST:event_jMenuItem2_view_all_productActionPerformed

    private void jMenuItem3_add_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3_add_productActionPerformed
        // TODO add your handling code here:
        Add_product ob = null;
            try {
                ob = new Add_product();
            } catch (SQLException ex) {
                Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
            }
        jDesktopPane2.add(ob); 
        Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob.getSize();
       ob.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
               
        ob.show();
    }//GEN-LAST:event_jMenuItem3_add_productActionPerformed

    private void jMenuItem4_add_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_add_customerActionPerformed
        Add_Account ob1;
            try {
                ob1 = new Add_Account();
                  jDesktopPane2.add(ob1);
        Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob1.getSize();
       ob1.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
     
        ob1.show();
            } catch (SQLException ex) {
                Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
            }
      
    }//GEN-LAST:event_jMenuItem4_add_customerActionPerformed

    private void jMenuItem8_view_all_billsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_view_all_billsActionPerformed
       All_Bill_Records ob2;
        try {
            ob2 = new All_Bill_Records();
             jDesktopPane2.add(ob2);
             Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob2.getSize();
       ob2.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
     
       ob2.show();
        } catch (SQLException ex) {
            Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_jMenuItem8_view_all_billsActionPerformed

    private void jMenuItem_update_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_update_customerActionPerformed
        
         Update_account ob3;
         ob3 = new Update_account();
         jDesktopPane2.add(ob3);
         Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob3.getSize();
       ob3.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
     
         ob3.show();
      
    }//GEN-LAST:event_jMenuItem_update_customerActionPerformed

    private void jMenuItem_update_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_update_productActionPerformed
       
         Update_product ob4;
         ob4 = new Update_product();
         jDesktopPane2.add(ob4);
         Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob4.getSize();
       ob4.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
     
         ob4.show();
    }//GEN-LAST:event_jMenuItem_update_productActionPerformed

    private void jMenuItem9_Add_product_qntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_Add_product_qntActionPerformed
         Add_qnt_new ob4;
         ob4 = new Add_qnt_new();
         jDesktopPane2.add(ob4);
         Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob4.getSize();
       ob4.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
    
         ob4.show();
    }//GEN-LAST:event_jMenuItem9_Add_product_qntActionPerformed

    private void jMenuItem10_add_customer_blncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10_add_customer_blncActionPerformed
        Add_customer_bln ob4;
         ob4 = new Add_customer_bln();
         jDesktopPane2.add(ob4);
         Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob4.getSize();
       ob4.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
    
         ob4.show();
    }//GEN-LAST:event_jMenuItem10_add_customer_blncActionPerformed

    private void jMenuItem12_dlt_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12_dlt_productActionPerformed
        Delete_product del =new  Delete_product();
        jDesktopPane2.add(del);
        Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = del.getSize();
       del.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
    
        del.show();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12_dlt_productActionPerformed

    private void jMenuItem13_delet_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13_delet_customerActionPerformed
         Delete_customer del =new  Delete_customer();
        jDesktopPane2.add(del);
        Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = del.getSize();
       del.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
    
        del.show();
    }//GEN-LAST:event_jMenuItem13_delet_customerActionPerformed

    private void jMenuItem14_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14_searchActionPerformed
        // TODO add your handling code here:
         Bill_search ser;
        try {
            ser = new  Bill_search();
            jDesktopPane2.add(ser);
            Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ser.getSize();
       ser.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
    
            ser.show();
        } catch (SQLException ex) {
            Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jMenuItem14_searchActionPerformed

    private void jMenuItem15_daily_saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15_daily_saleActionPerformed
        // TODO add your handling code here:
        Daily_sale dail;
        try {
            dail = new Daily_sale();
            jDesktopPane2.add(dail);
             Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = dail.getSize();
       dail.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
    
                    
        dail.show();
        } catch (SQLException ex) {
            Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem15_daily_saleActionPerformed

    private void jMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu11ActionPerformed
       
    }//GEN-LAST:event_jMenu11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
//        TODO add your handling code here:
//        Table_practise dail;
//        dail = new Table_practise();
//        jDesktopPane2.add(dail);
//        Dimension pareentSize = jDesktopPane2.getSize();
//        Dimension childSize = dail.getSize();
//        dail.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
//        dail.show();
        password_change_practise pass= new password_change_practise();
        jDesktopPane2.add(pass);
        Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = pass.getSize();
        pass.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
        pass.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6_log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6_log_outActionPerformed
       
                   Main_page.jMenu1_main_customer.setEnabled(false);
                   Main_page.jMenu7_main_product.setEnabled(false);
                   Main_page.jMenu8_file.setEnabled(true);
                   Main_page.jMenu1_bill_search.setEnabled(false);
                   Main_page.jMenu6_bill.setEnabled(false);
                   Main_page.jMenuItem6_log_out.setEnabled(true);
                   Main_page.jMenuItem7_log_in.setEnabled(true);
                   Main_page.jLabel1_status_user.setText("");
                   Main_page.jLabel1_name.setText("");
                   Main_page.jMenuItem7_add_new_accnt.setEnabled(false);
                   Main_page.jMenuItem7_change_pass.setEnabled(false);
                   Main_page.jLabel2_user_name_show.setText("");
    }//GEN-LAST:event_jMenuItem6_log_outActionPerformed

    private void jMenuItem7_log_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_log_inActionPerformed
          Login_window ob;
            try {
                ob = new Login_window();
                jDesktopPane2.add(ob);
         Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = ob.getSize();
        ob.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
        ob.show();
            } catch (InterruptedException ex) {
                Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_jMenuItem7_log_inActionPerformed

    private void jMenuItem7_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7_exitActionPerformed

    private void jMenuItem7_change_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_change_passActionPerformed
       Change_password change_p = new Change_password();
       jDesktopPane2.add(change_p);
         Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = change_p.getSize();
        change_p.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
        change_p.show();
        
    }//GEN-LAST:event_jMenuItem7_change_passActionPerformed

    private void jMenuItem7_add_new_accntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_add_new_accntActionPerformed
        Sign_up add_account = new Sign_up();
        jDesktopPane2.add(add_account);
        Dimension pareentSize = jDesktopPane2.getSize();
        Dimension childSize = add_account.getSize();
        add_account.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
        add_account.show();
    }//GEN-LAST:event_jMenuItem7_add_new_accntActionPerformed

    private void jMenuItem7_new_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_new_billActionPerformed
        New_bill ob1;
        try {
            ob1 = new New_bill();
            jDesktopPane2.add(ob1);
            Dimension pareentSize = jDesktopPane2.getSize();
            Dimension childSize = ob1.getSize();
            ob1.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);

            ob1.show();
        } catch (SQLException ex) {
            Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (PropertyVetoException ex) {
            Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7_new_billActionPerformed

    private void jMenuItem7_print_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_print_billActionPerformed
        
        print_bill printBill = new print_bill();
      
            jDesktopPane2.add(printBill);
            
            
            
            Dimension pareentSize = jDesktopPane2.getSize();
            Dimension childSize = printBill.getSize();
            printBill.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);

            printBill.show();
    }//GEN-LAST:event_jMenuItem7_print_billActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                 try {
                    {
                    Thread.sleep(0);
                    }
                    
                } catch (Exception e) {
                }
                 
                 
                 
                 
                try {
                    Class.forName(driver);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
                
        System.out.println("Drivers Loaded");
        try {
        con=  DriverManager.getConnection(connectionUrl, user, passwd);
        System.out.println("Connection Successed");
        
        
       
        // TODO code application logic here
    } catch (SQLException ex) {
        Logger.getLogger(DataBase_connection.class.getName()).log(Level.SEVERE, null, ex);
    }
                try {
                    //
                    new Main_page().setVisible(true);
                     Login_window login = new Login_window();
                    jDesktopPane2.add(login);
                     Dimension pareentSize = jDesktopPane2.getSize();
                     Dimension childSize = login.getSize();
                     login.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
                     login.show();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Main_page.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel1_name;
    public static javax.swing.JLabel jLabel1_status_user;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel2_user_name_show;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    public static javax.swing.JMenu jMenu1_Account;
    public static javax.swing.JMenu jMenu1_bill_search;
    public static javax.swing.JMenu jMenu1_main_customer;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    public static javax.swing.JMenu jMenu6_bill;
    private javax.swing.JMenu jMenu7;
    public static javax.swing.JMenu jMenu7_main_product;
    private javax.swing.JMenu jMenu8;
    public static javax.swing.JMenu jMenu8_file;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10_add_customer_blnc;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12_dlt_product;
    private javax.swing.JMenuItem jMenuItem13_delet_customer;
    private javax.swing.JMenuItem jMenuItem14_search;
    private javax.swing.JMenuItem jMenuItem15_daily_sale;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem2_view_all_product;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem3_add_product;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem4_add_customer;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    public static javax.swing.JMenuItem jMenuItem6_log_out;
    private javax.swing.JMenuItem jMenuItem6_view_all_customer;
    public static javax.swing.JMenuItem jMenuItem7_add_new_accnt;
    public static javax.swing.JMenuItem jMenuItem7_change_pass;
    private javax.swing.JMenuItem jMenuItem7_exit;
    public static javax.swing.JMenuItem jMenuItem7_log_in;
    private javax.swing.JMenuItem jMenuItem7_new_bill;
    private javax.swing.JMenuItem jMenuItem7_print_bill;
    private javax.swing.JMenuItem jMenuItem8_view_all_bills;
    private javax.swing.JMenuItem jMenuItem9_Add_product_qnt;
    private javax.swing.JMenuItem jMenuItem_update_customer;
    private javax.swing.JMenuItem jMenuItem_update_product;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    // End of variables declaration//GEN-END:variables
}
