/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahyar
 */
public class Sign_up extends javax.swing.JInternalFrame {

    /**
     * Creates new form Sign_up
     */
    public Sign_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1_type = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_user_name = new javax.swing.JTextField();
        jCheckBox1_show_password = new javax.swing.JCheckBox();
        jButton1_save = new javax.swing.JButton();
        jButton2_close = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5_status = new javax.swing.JLabel();
        jPasswordField1_pass = new javax.swing.JPasswordField();
        jPasswordField2_conform_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8_big_status = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Add New Account");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(17, 111, 204));
        jLabel1.setText("User Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 87, 90, -1));

        jLabel2.setForeground(new java.awt.Color(17, 111, 204));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 124, 90, -1));

        jLabel3.setForeground(new java.awt.Color(17, 111, 204));
        jLabel3.setText("Conform Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 161, 110, -1));

        jComboBox1_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        getContentPane().add(jComboBox1_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 152, -1));

        jLabel4.setForeground(new java.awt.Color(17, 111, 204));
        jLabel4.setText("Account Type");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 234, -1, 20));

        jTextField1_user_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField1_user_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_user_nameFocusGained(evt);
            }
        });
        getContentPane().add(jTextField1_user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 152, 26));

        jCheckBox1_show_password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1_show_password.setForeground(new java.awt.Color(11, 75, 139));
        jCheckBox1_show_password.setText("Show Password");
        jCheckBox1_show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_show_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1_show_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 152, -1));

        jButton1_save.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_save.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1_save.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_save.setText("Save");
        jButton1_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_saveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 263, 90, 36));

        jButton2_close.setBackground(new java.awt.Color(51, 51, 255));
        jButton2_close.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton2_close.setForeground(new java.awt.Color(255, 255, 255));
        jButton2_close.setText("Close");
        jButton2_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_closeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 263, 88, 36));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 19, 245));
        getContentPane().add(jLabel5_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 223, 25));

        jPasswordField1_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jPasswordField1_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1_passFocusGained(evt);
            }
        });
        jPasswordField1_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1_passActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 152, 26));

        jPasswordField2_conform_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jPasswordField2_conform_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2_conform_passFocusGained(evt);
            }
        });
        getContentPane().add(jPasswordField2_conform_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 152, 26));

        jLabel5.setFont(new java.awt.Font("AR BONNIE", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(104, 104, 232));
        jLabel5.setText("Sign up");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 52));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/add-user_resized.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 18, -1, 300));

        jLabel8_big_status.setFont(new java.awt.Font("AR BONNIE", 0, 24)); // NOI18N
        jLabel8_big_status.setForeground(new java.awt.Color(104, 104, 232));
        getContentPane().add(jLabel8_big_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 330, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Sign_up_ backgrounds.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_closeActionPerformed
        this.setVisible(false);     
        
    }//GEN-LAST:event_jButton2_closeActionPerformed

    private void jButton1_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_saveActionPerformed
        String check_name = jTextField1_user_name.getText();
        String check_pass = jPasswordField1_pass.getText();
        String check_conform_pass = jPasswordField2_conform_pass.getText();
        int status = 0;
        textfield_bal add_account = new textfield_bal();
        
        if((check_name.equalsIgnoreCase("")) || check_pass.equalsIgnoreCase("") ||check_conform_pass .equalsIgnoreCase(""))
            {
                    if(check_name.equalsIgnoreCase(""))
                            {
                            jTextField1_user_name.setBackground(Color.red);
                            jLabel5_status.setForeground(Color.red);
                            //jLabel5_status.setText("Please Enter Complete Information");
                             JOptionPane.showMessageDialog(null,"Please Enter Your Name" ,"Sign Up" , 2);
                         
                            }
                    if(check_pass.equalsIgnoreCase(""))
                            {
                            jPasswordField1_pass.setBackground(Color.red);
                            jLabel5_status.setForeground(Color.red);
                           // jLabel5_status.setText("Please Enter Complete Information");
                             JOptionPane.showMessageDialog(null,"Please Enter Your Password" ,"Change Password" , 2);
                         
                            }
                     if(check_conform_pass.equalsIgnoreCase(""))
                            {
                            jPasswordField2_conform_pass.setBackground(Color.red);
                            jLabel5_status.setForeground(Color.red);
                           // jLabel5_status.setText("Please Enter Complete Information");
                             JOptionPane.showMessageDialog(null,"Please Enter Your Conform New Password" ,"Change Password" , 2);
                         
                            }                  
                     
                     
            }
        else
            {
                if(jComboBox1_type.getSelectedIndex() == 0 )
                {
                        //admin
                    
                        if(check_pass.equals(check_conform_pass))
                        {
                               
                            boolean result = false;
                            try {
                                result = add_account.check_account_in_admin(check_name, check_pass);
                            } catch (SQLException ex) {
                                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
                            }
                                if(result)
                                {
                                         jLabel5_status.setForeground(Color.red);
                                        // jLabel5_status.setText("Account is Already Registered");
                                         jLabel8_big_status.setText("Account is Already Registered");
                                }
                                else
                                {
                                try {
                                   status = add_account.Add_account_admin(check_name, check_pass);
                                    if(status != 0)
                                    {
                                        jLabel5_status.setForeground(Color.GREEN);
                                        
                                       // jLabel5_status.setText("");
                                        jLabel8_big_status.setText("Admin Account is registered.");
                                    }
                                } catch (SQLException ex) {
                                    Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                }
                        }
                        else
                        {                           
                            jPasswordField2_conform_pass.setBackground(Color.red);
                            jPasswordField1_pass.setBackground(Color.red);
                            jLabel5_status.setForeground(Color.red);
                            //jLabel5_status.setText("Confrom Password is not same"); 
                            JOptionPane.showMessageDialog(null,"Confrom Password is not same" ,"Sign Up" , 1);
                         
                            
                        }
                        
                }
                else
                {
                    // user
                     if(check_pass.equals(check_conform_pass))
                        {
                               
                            boolean result = false;
                            try {
                                result = add_account.login_check_user(check_name, check_pass);
                            } catch (SQLException ex) {
                                Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
                            }
                                if(result)
                                {
                                         jLabel5_status.setForeground(Color.red);
                                         //jLabel5_status.setText("Account is Already Registered");
                                          jLabel8_big_status.setText("Account is Already Registered");
                             
                                         
                                }
                                else
                                {
                                try {
                                   status = add_account.Add_account_USER(check_name, check_pass);
                                    if(status != 0)
                                    {
                                        jLabel5_status.setForeground(Color.GREEN);
                                        
                                       ///jLabel5_status.setText("User Account is registered.");
                                        jLabel8_big_status.setText("User Account is registered.");
                              
                                    }
                                } catch (SQLException ex) {
                                    Logger.getLogger(Sign_up.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                }
                        }
                        else
                        {                           
                            jPasswordField2_conform_pass.setBackground(Color.red);
                            jPasswordField1_pass.setBackground(Color.red);
                            jLabel5_status.setForeground(Color.red);
                            //jLabel5_status.setText("Confrom Password is not same"); 
                            JOptionPane.showMessageDialog(null,"Confrom Password is not same" ,"Sign Up" , 1);
                         
                     
                        }
                        
                    
                    
                    
                }
            }
    }//GEN-LAST:event_jButton1_saveActionPerformed

    private void jCheckBox1_show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_show_passwordActionPerformed

         if(jCheckBox1_show_password.isSelected())
      {
          jPasswordField1_pass.setEchoChar((char)0);
          jPasswordField2_conform_pass.setEchoChar((char)0);
      }
         if(jCheckBox1_show_password.isSelected() == false)
      {
          jPasswordField1_pass.setEchoChar('*');
          jPasswordField2_conform_pass.setEchoChar('*');
      }// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1_show_passwordActionPerformed

    private void jPasswordField1_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1_passActionPerformed

    private void jPasswordField1_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1_passFocusGained
        // TODO add your handling code here:
        jPasswordField1_pass.setBackground(null);
    }//GEN-LAST:event_jPasswordField1_passFocusGained

    private void jPasswordField2_conform_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2_conform_passFocusGained
        // TODO add your handling code here:
        jPasswordField2_conform_pass.setBackground(null);
    }//GEN-LAST:event_jPasswordField2_conform_passFocusGained

    private void jTextField1_user_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_user_nameFocusGained
        jTextField1_user_name.setBackground(null);
    }//GEN-LAST:event_jTextField1_user_nameFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_save;
    private javax.swing.JButton jButton2_close;
    private javax.swing.JCheckBox jCheckBox1_show_password;
    private javax.swing.JComboBox jComboBox1_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5_status;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8_big_status;
    private javax.swing.JPasswordField jPasswordField1_pass;
    private javax.swing.JPasswordField jPasswordField2_conform_pass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1_user_name;
    // End of variables declaration//GEN-END:variables
}
