package Customer;


import Bill.Conform_bill_bal;
import Bill.New_bill;
import Bill.New_bill_bal;
import Login.Main_page;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class Add_customer_bln extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_customer_bln
     */
    DefaultComboBoxModel Customer_list;
    public Add_customer_bln() {
        initComponents();
         Customer_list();
        show_Customer_info_show();
        jTextField_customer_name_show.setEnabled(false);
        jTextField_remaing_bln_show.setEnabled(false);
        jTextField_add_blnce_show.setText("0");
    }

    public void Customer_list()
    {
       Account_bal ob = new Account_bal();
       Vector <String> v;
       
        try {
            v = ob.Customer_name();
             Customer_list= new DefaultComboBoxModel();
             for (String cb:v) {
               
                Customer_list.addElement(cb);
             //   JOptionPane.showMessageDialog(null,cb.getCustomer_name());
            }
           } catch (SQLException ex) {
            Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            jComboBox_customer_name.setModel(Customer_list);
             jTextField_customer_name_show.setText((String) jComboBox_customer_name.getSelectedItem()); 
             
    }
    
    
     public void show_Customer_info_show()
    {
        New_bill_bal ob  = new New_bill_bal();
        String s; 
        int Customer_balance= 0;
       
        // name
        s = (String) jComboBox_customer_name.getSelectedItem();
        jTextField_customer_name_show.setText(s);
        
        // balance
        
         try {
            Customer_balance = ob.getcustomer_balance(s);
         } catch (SQLException ex) {
             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
         }         
        jTextField_remaing_bln_show.setText(String.valueOf(Customer_balance));   
    }
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_customer_name = new javax.swing.JComboBox();
        jTextField_customer_name_show = new javax.swing.JTextField();
        jTextField_remaing_bln_show = new javax.swing.JTextField();
        jTextField_add_blnce_show = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jButton_closw = new javax.swing.JButton();
        jLabel_status = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jButton1_search = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9_background = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Customer Balance");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(17, 111, 204));
        jLabel1.setText("Select Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, -1));

        jLabel2.setForeground(new java.awt.Color(17, 111, 204));
        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, -1));

        jLabel3.setForeground(new java.awt.Color(17, 111, 204));
        jLabel3.setText("Remaining Customer Balance");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, -1));

        jLabel4.setForeground(new java.awt.Color(17, 111, 204));
        jLabel4.setText("Add Balance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        jComboBox_customer_name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_customer_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jComboBox_customer_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_customer_nameItemStateChanged(evt);
            }
        });
        jComboBox_customer_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_customer_nameActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 207, 26));

        jTextField_customer_name_show.setText("jTextField1");
        jTextField_customer_name_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_customer_name_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_customer_name_showActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_customer_name_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 207, 26));

        jTextField_remaing_bln_show.setText("jTextField2");
        jTextField_remaing_bln_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        getContentPane().add(jTextField_remaing_bln_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 207, 26));

        jTextField_add_blnce_show.setText("jTextField3");
        jTextField_add_blnce_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_add_blnce_show.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_add_blnce_showFocusGained(evt);
            }
        });
        jTextField_add_blnce_show.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField_add_blnce_showInputMethodTextChanged(evt);
            }
        });
        jTextField_add_blnce_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_add_blnce_showActionPerformed(evt);
            }
        });
        jTextField_add_blnce_show.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_add_blnce_showKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_add_blnce_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 207, 26));

        jButton_add.setBackground(new java.awt.Color(51, 51, 255));
        jButton_add.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Add");
        jButton_add.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 289, 84, 47));

        jButton_closw.setBackground(new java.awt.Color(51, 51, 255));
        jButton_closw.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton_closw.setForeground(new java.awt.Color(255, 255, 255));
        jButton_closw.setText("Close");
        jButton_closw.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_closw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closwActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_closw, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 84, 47));
        getContentPane().add(jLabel_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 293, 23));

        jLabel7.setForeground(new java.awt.Color(17, 111, 204));
        jLabel7.setText("Enter Customer ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, -1));

        jTextField1_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField1_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_idFocusLost(evt);
            }
        });
        jTextField1_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_idKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 207, -1));

        jButton1_search.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_search.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_search.setText("Search By ID");
        jButton1_search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 289, 130, 47));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/dollar-xxl.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 42, 240, 270));

        jLabel10.setFont(new java.awt.Font("AR BONNIE", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(104, 104, 232));
        jLabel10.setText("Add Customer Balance");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 14, 290, 48));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 14, 240));

        jLabel9_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel9_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_customer_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_customer_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_customer_nameActionPerformed

    private void jTextField_customer_name_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_customer_name_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_customer_name_showActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
jTextField1_id.setBackground(Color.white);
        if(jTextField_customer_name_show.getText().equalsIgnoreCase(""))
{
     JOptionPane.showMessageDialog(null,"Customer Info is Not Available" , this.title, 0);
}
else
{
        
         String  check_bln = jTextField_add_blnce_show.getText();
           jTextField_add_blnce_show.setBackground(null);
            if((check_bln.equalsIgnoreCase("")) || check_bln.equalsIgnoreCase("0"))
        {
            jTextField_add_blnce_show.setBackground(Color.red);
            jLabel_status.setForeground(Color.red);
            //jLabel_status.setText("Please Enter Complete Information");
            JOptionPane.showMessageDialog(null,"Please Enter Complete Customer Info" ,"Customer Updates" , 2);
                  
            
        }
            else{
                
                
                 
                 int option = JOptionPane.showConfirmDialog(null, "Do you Want to Add Customer Balance..??", "Add Balance", JOptionPane.YES_NO_OPTION , 0);
    
                 if(option == 0 )
                  {
                     
        String customer_name = jTextField_customer_name_show.getText();
       int add_blnce = Integer.parseInt(jTextField_add_blnce_show.getText());
        Account_bal add_bln = new Account_bal();
         try {
             add_bln.add_customer_blnce(customer_name, add_blnce);
             
         } catch (SQLException ex) {
             Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
         }
         jLabel_status.setForeground(Color.GREEN);
         
         //jLabel_status.setText("Balance is Added");
         JOptionPane.showMessageDialog(null,"Customer Balance is Updated Successfully." ,"Add Balance Successfully" , 1);
         jTextField_add_blnce_show.setText("0");
         Customer_list();
         show_Customer_info_show();
                  }
            }
}
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jComboBox_customer_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_customer_nameItemStateChanged
        
        show_Customer_info_show();
    }//GEN-LAST:event_jComboBox_customer_nameItemStateChanged

    private void jTextField_add_blnce_showInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField_add_blnce_showInputMethodTextChanged
    
    }//GEN-LAST:event_jTextField_add_blnce_showInputMethodTextChanged

    private void jButton_closwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closwActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton_closwActionPerformed

    private void jTextField_add_blnce_showKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_add_blnce_showKeyPressed
       
        int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
            jTextField_add_blnce_show.setEditable(true);
            jTextField_add_blnce_show.setBackground(Color.yellow);
            jLabel_status.setText("");
        }
        else
        {
           jTextField_add_blnce_show.setEditable(false);
            jTextField_add_blnce_show.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
        jLabel_status.setText("Please Enter Only Numeric Value");
        }
    }//GEN-LAST:event_jTextField_add_blnce_showKeyPressed

    private void jTextField_add_blnce_showFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_add_blnce_showFocusGained
        jTextField_add_blnce_show.setBackground(null);
        jLabel_status.setText("");
    }//GEN-LAST:event_jTextField_add_blnce_showFocusGained

    private void jButton1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_searchActionPerformed

        jLabel_status.setText("");
        
        if(String.valueOf(jTextField1_id.getText()).equalsIgnoreCase(""))
        {
           
            
            jTextField1_id.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
            //jLabel_status.setText("Enter ID First");
             JOptionPane.showMessageDialog(this, "Please Enter Customer ID First", "Search ID", 2);
        }
        else{
        int id =Integer.parseInt(jTextField1_id.getText());
      
        
        PreparedStatement ps = null;
        ResultSet rs = null;
        String Query = "select customer_name , customer_balnce from account\n" +
       " where \n" +
       " account_id = ?";
         try {       
             ps=Main_page.con.prepareStatement(Query);
             ps.setInt(1, id); 
            rs = ps.executeQuery();
             int count = 0;
            while(rs.next())
            {
                
             jTextField_customer_name_show.setText(rs.getString("customer_name"));
             jTextField_remaing_bln_show.setText(rs.getString("customer_balnce"));
            count++;
                }
                 Account_bal ob = new Account_bal();
            String customer_name;
            customer_name = ob.get_single_customer_name(id);
            jComboBox_customer_name.setSelectedItem(customer_name);
              
                if(count == 0)
                {
                    jLabel_status.setForeground(Color.red);
                    JOptionPane.showMessageDialog(this, "Please Enter Correct ID", "Search ID", 2);
             
                    //jLabel_status.setText("ID NOT FOUND");
                }
            
         } catch (SQLException ex) {
             Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
         }
        }   
    }//GEN-LAST:event_jButton1_searchActionPerformed

    private void jTextField1_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_idFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idFocusLost

    private void jTextField1_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_idFocusGained
       jTextField1_id.setBackground(Color.WHITE);
        jLabel_status.setText("");
    }//GEN-LAST:event_jTextField1_idFocusGained

    private void jTextField1_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_idKeyPressed
        int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField1_id.setEditable(true);
          jTextField1_id.setBackground(Color.yellow);
            jLabel_status.setText("");
        }
        else
        {
           jTextField1_id.setEditable(false);
             jTextField1_id.setBackground(Color.RED);
           jLabel_status.setForeground(Color.red);
            jLabel_status.setText("Please Enter Only Numeric Value");
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idKeyPressed

    private void jTextField_add_blnce_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_add_blnce_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_add_blnce_showActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_search;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_closw;
    private javax.swing.JComboBox jComboBox_customer_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9_background;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField_add_blnce_show;
    private javax.swing.JTextField jTextField_customer_name_show;
    private javax.swing.JTextField jTextField_remaing_bln_show;
    // End of variables declaration//GEN-END:variables
}
