package Customer;


import Bill.New_bill;
import Login.Main_page;
import static Login.Main_page.jDesktopPane2;
import Products.Add_product;
import com.sun.glass.events.KeyEvent;
import com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class Add_Account extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_Account
     */
    public Add_Account() throws SQLException {
        initComponents();
        jTextField1_id.setEnabled(false);
        jButton1.setEnabled(false);
        int id;
        Account_bal new_id = new Account_bal();
        id = new_id.get_New_customer_id();
        jTextField1_id.setText(String.valueOf(id+1));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_status = new javax.swing.JLabel();
        jTextField_customer_name = new javax.swing.JTextField();
        jTextField_balance = new javax.swing.JTextField();
        jLabel_Customer_name = new javax.swing.JLabel();
        jLabel_balance = new javax.swing.JLabel();
        jButton_Add = new javax.swing.JButton();
        jButton1_reeset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Customer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 274, 23));

        jTextField_customer_name.setToolTipText("Enter Customer Name");
        jTextField_customer_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_customer_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_customer_nameFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 114, 221, 26));

        jTextField_balance.setToolTipText("Enter Customer Balance");
        jTextField_balance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_balance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_balanceFocusGained(evt);
            }
        });
        jTextField_balance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_balanceKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 152, 221, 26));

        jLabel_Customer_name.setForeground(new java.awt.Color(17, 111, 204));
        jLabel_Customer_name.setText("Customer Name");
        getContentPane().add(jLabel_Customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 102, -1));

        jLabel_balance.setForeground(new java.awt.Color(17, 111, 204));
        jLabel_balance.setText("Balance");
        getContentPane().add(jLabel_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, 102, 20));

        jButton_Add.setBackground(new java.awt.Color(51, 51, 255));
        jButton_Add.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton_Add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Add.setText("Add");
        jButton_Add.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, 90, 47));

        jButton1_reeset.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_reeset.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1_reeset.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_reeset.setText("Reset");
        jButton1_reeset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1_reeset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_reesetActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_reeset, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 231, 80, 47));

        jLabel2.setForeground(new java.awt.Color(17, 111, 204));
        jLabel2.setText("Customer ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, 102, -1));

        jTextField1_id.setToolTipText("Customer ID");
        jTextField1_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        getContentPane().add(jTextField1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 76, 221, 26));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD NEW ??");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 231, 140, 47));

        jLabel5.setFont(new java.awt.Font("AR BONNIE", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(104, 104, 232));
        jLabel5.setText("Add Customer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 14, 248, 48));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 51, 15, 179));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/icon-services-client.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 19, -1, 264));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/add_cutomer_backg.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
       
        String check = (String)jTextField_customer_name.getText();
        String  check_bln = jTextField_balance.getText();
           jTextField_customer_name.setBackground(null);
        jTextField_balance.setBackground(null);
        
        if((check.equalsIgnoreCase("")) || check_bln.equalsIgnoreCase("")|| check_bln.equalsIgnoreCase("0"))
        {
            
            if((check.equalsIgnoreCase("")) && (check_bln.equalsIgnoreCase("")|| check_bln.equalsIgnoreCase("0")))
            {
                jTextField_customer_name.setBackground(Color.red);
                jTextField_balance.setBackground(Color.red);
                JOptionPane.showMessageDialog(null,"Please Enter Complete Customer Info" ,"New Customer" , 2);
            }
                else
            {
                           if(check.equalsIgnoreCase(""))
                        {
                       jTextField_customer_name.setBackground(Color.red);
                        jLabel_status.setForeground(Color.red);
                       // jLabel_status.setText("Please Enter Complete Information");
                        JOptionPane.showMessageDialog(null,"Please Enter Customer Name" ,"New Customer" , 1);
                                                  
                        }
                        if(check_bln.equalsIgnoreCase("") || check_bln.equalsIgnoreCase("0"))
                        {
                        jTextField_balance.setBackground(Color.red);
                        jLabel_status.setForeground(Color.red);
                          JOptionPane.showMessageDialog(null,"Please Enter Customer Balance" ,"New Customer" , 1);
                        //jLabel_status.setText("Please Enter Complete Information");
                        }
                        }
        }
        
        
        
        else{
            
             int option = JOptionPane.showConfirmDialog(null, "Do you Want to Add New Customer..??", "Add Customer", JOptionPane.YES_NO_OPTION , 0);
    
            if(option == 0 )

            {
                
        Account_bal ob = new Account_bal();
       int row = 0;
       int balance = (Integer.parseInt(jTextField_balance.getText()));
    
        try {
           row = ob.AddAccount(jTextField_customer_name.getText(), balance);       
           if(row != 0)
        {
          jLabel_status.setForeground(Color.GREEN);
          //jLabel_status.setText("Account is Add");  
          JOptionPane.showMessageDialog(null,"New Customer is Successfully Added" ,"New Customer" , 1);
          jButton_Add.setEnabled(false);
          jButton1_reeset.setEnabled(false);
          jButton1.setEnabled(true);
        }
        else
        {
            jLabel_status.setForeground(Color.RED);
           jLabel_status.setText("Product is not Add"); 
        }
        } catch (SQLException ex) {
            Logger.getLogger(Add_product.class.getName()).log(Level.SEVERE, null, ex);
        }
                  }
        }
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton1_reesetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_reesetActionPerformed
        
        jTextField_balance.setText("");
        jTextField_customer_name.setText("");
        jLabel_status.setText("");
        jTextField_balance.setBackground(null);
        jTextField_customer_name.setBackground(null);
    }//GEN-LAST:event_jButton1_reesetActionPerformed

    private void jTextField_balanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_balanceKeyPressed
        int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
            jTextField_balance.setEditable(true);
            jTextField_balance.setBackground(Color.yellow);
            jLabel_status.setText("");
        }
        else
        {
           jTextField_balance.setEditable(false);
            jTextField_balance.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
            jLabel_status.setText("Please Enter Only Numeric Value");
        }
    }//GEN-LAST:event_jTextField_balanceKeyPressed

    private void jTextField_customer_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_customer_nameFocusGained
        // TODO add your handling code here:
        jTextField_customer_name.setBackground(null);
    }//GEN-LAST:event_jTextField_customer_nameFocusGained

    private void jTextField_balanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_balanceFocusGained
        jTextField_balance.setBackground(null);
    }//GEN-LAST:event_jTextField_balanceFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.setVisible(false);
       
         try {
             
            // open new bill
             Add_Account new_entry = new Add_Account();
             Main_page.jDesktopPane2.add(new_entry);
              Dimension pareentSize = jDesktopPane2.getSize();
             Dimension childSize = new_entry.getSize();
             new_entry.setLocation((pareentSize.width - childSize.width)/2, (pareentSize.height - childSize.height)/2);
             new_entry.setVisible(true);
         }   catch (SQLException ex) {
             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_reeset;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_Customer_name;
    private javax.swing.JLabel jLabel_balance;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField_balance;
    private javax.swing.JTextField jTextField_customer_name;
    // End of variables declaration//GEN-END:variables
}
