package Customer;




import Customer.Account_bal;
import Bill.Conform_bill_bal;
import Bill.New_bill;
import Bill.New_bill_bal;
import Login.Main_page;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class Update_account extends javax.swing.JInternalFrame {

    /**
     * Creates new form Update_account
     */
     DefaultComboBoxModel Customer_list;
    public Update_account() {
        initComponents();
        Customer_list();
        show_Customer_info_show();
         jTextField_new_blnc_show.requestFocus();
        jTextField1_new_name_show.setEnabled(false);
        jTextField_customer_name_show.setEnabled(false);
        jTextField_old_balnace_show.setEnabled(false);
       // jTextField_old_balnace_show.setText("0");
         jTextField_new_blnc_show.requestFocus();
      //  jTextField_new_blnc_show.setText("");
        //jTextField_new_blnc_show.setFocusable(true);
        jTextField_new_blnc_show.requestFocus();
        
    }

    
     public void Customer_list()
    {
       Account_bal ob = new Account_bal();
       Vector <String> v;
       
        try {
            v = ob.Customer_name();
             Customer_list= new DefaultComboBoxModel();
             for (String cb:v) {
               
                Customer_list.addElement(cb);
             //   JOptionPane.showMessageDialog(null,cb.getCustomer_name());
            }
           } catch (SQLException ex) {
            Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            jComboBox_customer.setModel(Customer_list);
             jTextField_customer_name_show.setText((String) jComboBox_customer.getSelectedItem()); 
             
    }

     
     
     public void show_Customer_info_show()
    {
        New_bill_bal ob  = new New_bill_bal();
        String s; 
        int Customer_balance= 0;
       
        // name
        s = (String) jComboBox_customer.getSelectedItem();
        jTextField_customer_name_show.setText(s);
        
        // balance
        
         try {
            Customer_balance = ob.getcustomer_balance(s);
         } catch (SQLException ex) {
             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
         }         
        jTextField_old_balnace_show.setText(String.valueOf(Customer_balance));   
    }
     
     public void search_by_id(int id) throws SQLException
     {
        
      
        
     }
     
//     public int update_customer_balnce()
//     {
//         
//      int row = 0;
//        PreparedStatement ps =null;
//        ResultSet rs=null;
//         
//        String Query = "insert into account (customer_name , customer_balnce )  values (? , ?)";
//        ps=DataBase_connection.con.prepareStatement(Query);
//        ps.setString(1, customer_name);
//        ps.setInt(2, balnce);
//        
//        row =ps.executeUpdate();
//        
//        return row;
//     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_customer = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_old_balnace_show = new javax.swing.JTextField();
        jTextField_new_blnc_show = new javax.swing.JTextField();
        jButton_update = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_customer_name_show = new javax.swing.JTextField();
        jLabel_status = new javax.swing.JLabel();
        jCheckBox1_customer_name_change = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_new_name_show = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jButton1_search = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Update Customer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_customer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Customer Name", "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_customer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jComboBox_customer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_customerItemStateChanged(evt);
            }
        });
        jComboBox_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_customerActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 119, 141, 26));

        jLabel4.setForeground(new java.awt.Color(17, 111, 204));
        jLabel4.setText("Enter New Balance");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 338, -1, -1));

        jLabel3.setForeground(new java.awt.Color(17, 111, 204));
        jLabel3.setText("Current Balance");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel2.setForeground(new java.awt.Color(17, 111, 204));
        jLabel2.setText("Select Customer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, -1, 20));

        jTextField_old_balnace_show.setText("Old balance");
        jTextField_old_balnace_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        getContentPane().add(jTextField_old_balnace_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 288, 141, 26));

        jTextField_new_blnc_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_new_blnc_show.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_new_blnc_showFocusGained(evt);
            }
        });
        jTextField_new_blnc_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_new_blnc_showActionPerformed(evt);
            }
        });
        jTextField_new_blnc_show.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_new_blnc_showKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_new_blnc_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 332, 141, 26));

        jButton_update.setBackground(new java.awt.Color(51, 51, 255));
        jButton_update.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("Update");
        jButton_update.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 75, 42));

        jButton_Cancel.setBackground(new java.awt.Color(51, 51, 255));
        jButton_Cancel.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancel.setText("Close");
        jButton_Cancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 75, 42));

        jLabel5.setForeground(new java.awt.Color(17, 111, 204));
        jLabel5.setText("Customer Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, -1, -1));

        jTextField_customer_name_show.setText("Customer Name");
        jTextField_customer_name_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        getContentPane().add(jTextField_customer_name_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 163, 141, 26));
        getContentPane().add(jLabel_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 376, 257, 23));

        jCheckBox1_customer_name_change.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1_customer_name_change.setForeground(new java.awt.Color(11, 75, 139));
        jCheckBox1_customer_name_change.setText("Change Name");
        jCheckBox1_customer_name_change.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1_customer_name_changeItemStateChanged(evt);
            }
        });
        jCheckBox1_customer_name_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1_customer_name_changeActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1_customer_name_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 247, -1, -1));

        jLabel6.setForeground(new java.awt.Color(17, 111, 204));
        jLabel6.setText("Enter New Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        jTextField1_new_name_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField1_new_name_show.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_new_name_showFocusGained(evt);
            }
        });
        getContentPane().add(jTextField1_new_name_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 203, 141, 26));

        jLabel7.setForeground(new java.awt.Color(17, 111, 204));
        jLabel7.setText("Enter Customer Id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        jTextField1_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField1_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_idFocusGained(evt);
            }
        });
        jTextField1_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_idKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 75, 141, 26));

        jButton1_search.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_search.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_search.setText("Search by ID");
        jButton1_search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 140, 42));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 75, 16, 308));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/www.GIFCreator.me_c408oC.gif"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 75, 324, 308));

        jLabel9.setFont(new java.awt.Font("AR BONNIE", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(104, 104, 232));
        jLabel9.setText("Update Customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, 230, 52));

        jLabel1.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/update_customer_backgrond.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_customerActionPerformed

    private void jComboBox_customerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_customerItemStateChanged
        show_Customer_info_show();
        jTextField_new_blnc_show.setText("");
        jTextField1_new_name_show.setText("");
        jLabel_status.setText("");
    }//GEN-LAST:event_jComboBox_customerItemStateChanged

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
if(jTextField_customer_name_show.getText().equalsIgnoreCase(""))
{
     JOptionPane.showMessageDialog(null,"Customer Info is Not Available" ,"Update" , 0);
}
else
{
    

        
        String  check_bln = jTextField_new_blnc_show.getText();
           jTextField_new_blnc_show.setBackground(null);
           
           
           if(jCheckBox1_customer_name_change.isSelected() == false)
           {
                   if((check_bln.equalsIgnoreCase("")) || check_bln.equalsIgnoreCase("0"))
                      {
                     jTextField_new_blnc_show.setBackground(Color.red);
                     jLabel_status.setForeground(Color.red);
                    // jLabel_status.setText("Please Enter Complete Information");
                     JOptionPane.showMessageDialog(null,"Please Enter Customer New Balance" ,"New Balance Alert" , 1);
                     }
                else{
                
                 int option = JOptionPane.showConfirmDialog(null, "Do you Want to Update..??", "Update", JOptionPane.YES_NO_OPTION , 0);
    
                 if(option == 0 )
                  {
                      
                String customer_name = jTextField_customer_name_show.getText();
                int new_blnce = Integer.parseInt(jTextField_new_blnc_show.getText());
                Account_bal update_bln = new Account_bal();
                 try {
                     update_bln.update_customer_balnce(customer_name, new_blnce);

                 } catch (SQLException ex) {
                     Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 jLabel_status.setForeground(Color.GREEN);
                //jLabel_status.setText("Account Updated");
                 JOptionPane.showMessageDialog(null,"Customer Is Successfully Updated." ,"Customer Update" , 0);
                Customer_list();
                show_Customer_info_show();
                      }
                   
                   }
           
            
           }
           else
           {
               String updated_name = jTextField1_new_name_show.getText();
                if(updated_name.equalsIgnoreCase("") ||(check_bln.equalsIgnoreCase("")) || check_bln.equalsIgnoreCase("0"))
                {
                    
                    if(updated_name.equalsIgnoreCase("") && (  (check_bln.equalsIgnoreCase("")) || check_bln.equalsIgnoreCase("0")  ))
                    {
                        jTextField1_new_name_show.setBackground(Color.red);
                        jLabel_status.setForeground(Color.red);
                        jTextField_new_blnc_show.setBackground(Color.red);
                             jLabel_status.setForeground(Color.red);
                        JOptionPane.showMessageDialog(null,"Please Enter Complete Customer Info" ,"Customer Updates" , 2);
                    }
                    else
                    {
                        
                    
                            if(updated_name.equalsIgnoreCase(""))
                            {
                             jTextField1_new_name_show.setBackground(Color.red);
                             jLabel_status.setForeground(Color.red);
                            // jLabel_status.setText("Please Enter Complete Information");
                             JOptionPane.showMessageDialog(null,"Please Enter Customer Name" ,"New Balance Alert" , 1);
                            }
                            if((check_bln.equalsIgnoreCase("")) || check_bln.equalsIgnoreCase("0"))
                            {
                             jTextField_new_blnc_show.setBackground(Color.red);
                             jLabel_status.setForeground(Color.red);
                           //  jLabel_status.setText("Please Enter Complete Information");
                              JOptionPane.showMessageDialog(null,"Please Enter Customer Balance" ,"New Balance Alert" , 1);
                            }
                    }
                
                }
               else
                {
                     
                 int option = JOptionPane.showConfirmDialog(null, "Do you Want to Update..??", "Update", JOptionPane.YES_NO_OPTION , 0);
    
                 if(option == 0 )
                  {
                    // balnce update
                        String customer_name = jTextField_customer_name_show.getText();
                      int new_blnce = Integer.parseInt(jTextField_new_blnc_show.getText());
                      Account_bal update_bln = new Account_bal();
                       try {
                           update_bln.update_customer_balnce(customer_name, new_blnce);

                       } catch (SQLException ex) {
                           Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
                       }
                       
                   try {
                       // name update
                       
                       update_bln.update_customer_Name(updated_name, customer_name);
                   } catch (SQLException ex) {
                       Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
                   }
                     jLabel_status.setForeground(Color.GREEN);
                      //jLabel_status.setText("Account Updated");
                     
                      JOptionPane.showMessageDialog(null,"Customer Is Successfully Updated." ,"Customer Update" , 0);
                
                      Customer_list();
                      show_Customer_info_show();
                      jTextField1_new_name_show.setText("");
                      jTextField_new_blnc_show.setText("");
                      jTextField1_id.setText("");
                  }
                  }
               
           }
}          
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jTextField_new_blnc_showKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_new_blnc_showKeyPressed
       jLabel_status.setText("");
        int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
            jTextField_new_blnc_show.setEditable(true);
            jTextField_new_blnc_show.setBackground(Color.yellow);
            jLabel_status.setText("");
        }
        else
        {
            jTextField_new_blnc_show.setEditable(false);
            jTextField_new_blnc_show.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
            jLabel_status.setText("Please Enter Only Numeric Value");
            
        }
    }//GEN-LAST:event_jTextField_new_blnc_showKeyPressed

    private void jCheckBox1_customer_name_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1_customer_name_changeActionPerformed
       
    }//GEN-LAST:event_jCheckBox1_customer_name_changeActionPerformed

    private void jCheckBox1_customer_name_changeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1_customer_name_changeItemStateChanged
  if(jCheckBox1_customer_name_change.isSelected())
        {
            jTextField1_new_name_show.setEnabled(true);
            jTextField1_new_name_show.requestFocus();
        }
        if(jCheckBox1_customer_name_change.isSelected() == false)
        {
            jTextField1_new_name_show.setEnabled(false);
        }       
        
    }//GEN-LAST:event_jCheckBox1_customer_name_changeItemStateChanged

    private void jTextField_new_blnc_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_new_blnc_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_new_blnc_showActionPerformed

    private void jTextField_new_blnc_showFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_new_blnc_showFocusGained
        // TODO add your handling code here:
        jTextField_new_blnc_show.setBackground(null);
        jLabel_status.setText("");
    }//GEN-LAST:event_jTextField_new_blnc_showFocusGained

    private void jTextField1_new_name_showFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_new_name_showFocusGained
        // TODO add your handling code here:
        jTextField1_new_name_show.setBackground(null);
        jLabel_status.setText("");
    }//GEN-LAST:event_jTextField1_new_name_showFocusGained

    private void jButton1_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_searchActionPerformed

        jLabel_status.setText("");
        
        if(String.valueOf(jTextField1_id.getText()).equalsIgnoreCase(""))
        {
            
            
            jTextField1_id.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
           // jLabel_status.setText("Enter ID First");
            JOptionPane.showMessageDialog(this, "Please Enter Customer ID First", "Search ID", 2);
        }
        else{
        
        int id = Integer.parseInt(jTextField1_id.getText());
        PreparedStatement ps = null;
        ResultSet rs = null;
        String Query = " select customer_name , customer_balnce from account\n" +
       " where \n" +
       " account_id = ?";
         try {       
             ps=Main_page.con.prepareStatement(Query);
             ps.setInt(1, id); 
            rs = ps.executeQuery();
            int count = 0;
            while(rs.next())
            {
             jTextField_customer_name_show.setText(rs.getString("customer_name"));
             jTextField_old_balnace_show.setText(rs.getString("customer_balnce"));
             count++;
            }
            
            Account_bal ob = new Account_bal();
            String customer_name;
            customer_name = ob.get_single_customer_name(id);
            jComboBox_customer.setSelectedItem(customer_name);
                if(count == 0)
                {
                    jLabel_status.setForeground(Color.red);
                    //jLabel_status.setText("ID NOT FOUND");
                     JOptionPane.showMessageDialog(this, "Please Enter Correct ID", "Search ID", 2);
                }
            
            
         } catch (SQLException ex) {
             Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        }
// after having  some customer name in field // else block

        
    }//GEN-LAST:event_jButton1_searchActionPerformed

    private void jTextField1_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_idFocusGained
jTextField1_id.setBackground(Color.white);
        jLabel_status.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idFocusGained

    private void jTextField1_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_idKeyPressed
      // TODO add your handling code here:
         jLabel_status.setText("");
        int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField1_id.setEditable(true);
             jTextField1_id.setBackground(Color.yellow);
            jLabel_status.setText("");
        }
        else
        {
             jTextField1_id.setEditable(false);
             jTextField1_id.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
            jLabel_status.setText("Please Enter Only Numeric Value");
            
        }
    }//GEN-LAST:event_jTextField1_idKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_search;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_update;
    private javax.swing.JCheckBox jCheckBox1_customer_name_change;
    private javax.swing.JComboBox jComboBox_customer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField1_new_name_show;
    private javax.swing.JTextField jTextField_customer_name_show;
    private javax.swing.JTextField jTextField_new_blnc_show;
    private javax.swing.JTextField jTextField_old_balnace_show;
    // End of variables declaration//GEN-END:variables
}
