package Customer;

import Data_base_Conection.DataBase_connection;
import Login.Main_page;
import static Login.Main_page.con;
import Products.View_product;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class View_Accounts extends javax.swing.JInternalFrame {

    /**
     * Creates new form View_Accounts
     */
    public View_Accounts()throws SQLException {
        initComponents();
         jButton1_search_Customer_print.setEnabled(false);
        PreparedStatement ps =null;
        ResultSet rs=null;
       /// Vector <String> a = new Vector<>();
        String Query="select * from account";
        ps=Main_page.con.prepareStatement(Query);
        rs=ps.executeQuery();
        
        ResultSetMetaData rsmetadata = rs.getMetaData();
        int columbs = rsmetadata.getColumnCount();
        DefaultTableModel dtm  = new DefaultTableModel();
       Vector colums_name = new Vector();
        Vector datarows = new Vector();
        for(int  i = 1 ; i <= columbs ; i++){
            colums_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(colums_name);       
        while(rs.next())
        {
           datarows = new Vector();
           for(int j = 1 ; j <=columbs ; j++)
           {
               datarows.addElement(rs.getString(j));
           }
           dtm.addRow(datarows);
           
        }
        jTable1.setModel(dtm);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1_refresh = new javax.swing.JButton();
        jButton2_search = new javax.swing.JButton();
        jTextField1_id = new javax.swing.JTextField();
        jLabel3_status = new javax.swing.JLabel();
        jButton1_Print_all_Record = new javax.swing.JButton();
        jButton1_search_Customer_print = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3_back_grond = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Account List");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(0, 153, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Account ID", "Customer name", "Customer balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 102, 0));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 793, 258));

        jButton1_refresh.setBackground(new java.awt.Color(255, 102, 0));
        jButton1_refresh.setText("Refresh Records");
        jButton1_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_refreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 70, -1, 31));

        jButton2_search.setBackground(new java.awt.Color(255, 102, 0));
        jButton2_search.setText("Search By ID");
        jButton2_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 70, -1, 31));

        jTextField1_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_idFocusGained(evt);
            }
        });
        jTextField1_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_idKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 148, -1));

        jLabel3_status.setText("jLabel3");
        getContentPane().add(jLabel3_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 78, 187, -1));

        jButton1_Print_all_Record.setBackground(new java.awt.Color(255, 102, 0));
        jButton1_Print_all_Record.setText("Print All Records");
        jButton1_Print_all_Record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Print_all_RecordActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Print_all_Record, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 382, -1, 25));

        jButton1_search_Customer_print.setBackground(new java.awt.Color(255, 102, 0));
        jButton1_search_Customer_print.setText("Print Search Customer");
        jButton1_search_Customer_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_search_Customer_printActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_search_Customer_print, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 382, 194, 25));

        jLabel4.setFont(new java.awt.Font("AR BONNIE", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("All available Customers");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, 330, 52));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Enter Product ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 125, 20));

        jLabel3_back_grond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Customer/beautiful_light_blue_sky-wallpaper-1366x768.jpg"))); // NOI18N
        getContentPane().add(jLabel3_back_grond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_refreshActionPerformed
        try {
            
               
        PreparedStatement ps =null;
        ResultSet rs=null;
       /// Vector <String> a = new Vector<>();
        String Query="select * from account";
        ps=Main_page.con.prepareStatement(Query);
        rs=ps.executeQuery();
        
             
               
             ResultSetMetaData rsmetadata = rs.getMetaData();
        int columbs = rsmetadata.getColumnCount();
        DefaultTableModel dtm  = new DefaultTableModel();
       Vector colums_name = new Vector();
        Vector datarows = new Vector();
        for(int  i = 1 ; i <= columbs ; i++){
            colums_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(colums_name); 
            
            while(rs.next())
            {
                datarows = new Vector();
                for(int j = 1 ; j <=columbs ; j++)
                {
                    datarows.addElement(rs.getString(j));
                }
                dtm.addRow(datarows);
                
            }
            
            
            
            jTable1.setModel(dtm);
            jButton1_search_Customer_print.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(View_Accounts.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextField1_id.setBackground(Color.WHITE);
       jLabel3_status.setText("");
        
    }//GEN-LAST:event_jButton1_refreshActionPerformed

    private void jButton2_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_searchActionPerformed
    jLabel3_status.setText("");

        if(String.valueOf(jTextField1_id.getText()).equalsIgnoreCase(""))
        {

            jTextField1_id.setBackground(Color.RED);
            jLabel3_status.setForeground(Color.red);
           // jLabel3_status.setText("Enter Customer ID First");
              JOptionPane.showMessageDialog(this, "Please Enter Customer ID First", "Search ID", 2);
        }
        else{
        
        
        
        
        
        
        int id = Integer.parseInt(jTextField1_id.getText());
        PreparedStatement ps =null;
        ResultSet rs=null;
       /// Vector <String> a = new Vector<>();
        String Query="select * from account \n" +
"where \n" +
"account_id = ?";
        try {
            
            
            
            ps=Main_page.con.prepareStatement(Query);
             ps.setInt(1, id);    
           rs=ps.executeQuery();
        
        ResultSetMetaData rsmetadata = rs.getMetaData();
        int columbs = rsmetadata.getColumnCount();
        DefaultTableModel dtm  = new DefaultTableModel();
       Vector colums_name = new Vector();
        Vector datarows = new Vector();
        for(int  i = 1 ; i <= columbs ; i++){
            colums_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(colums_name);       
        while(rs.next())
        {
           datarows = new Vector();
           for(int j = 1 ; j <=columbs ; j++)
           {
               datarows.addElement(rs.getString(j));
           }
           dtm.addRow(datarows);
           
        }
        jTable1.setModel(dtm);
        jButton1_search_Customer_print.setEnabled(true);
      } catch (SQLException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }
        
    }//GEN-LAST:event_jButton2_searchActionPerformed

    private void jTextField1_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_idFocusGained
       jTextField1_id.setBackground(Color.WHITE);
       jLabel3_status.setText("");
    }//GEN-LAST:event_jTextField1_idFocusGained

    private void jButton1_Print_all_RecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Print_all_RecordActionPerformed
      
         try {
            // C:\Users\Shahyar\Desktop
            //JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Report_practise\\report2.jrxml");
              //String sql =  "select * from account";
              JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Inventory_managment\\Reports\\View Customer\\All_customers.jrxml");

             String sql =  "select * from account";
            
            
            JRDesignQuery  newquer  = new JRDesignQuery();
             newquer.setText(sql);
            jd.setQuery(newquer);
            JasperReport jr =  JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null , con);
             JasperViewer.viewReport(jp,false);
        } catch (JRException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jButton1_Print_all_RecordActionPerformed

    private void jButton1_search_Customer_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_search_Customer_printActionPerformed
      if(jTable1.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this,"No Record Available");
        }
        else
        {
            String  id = jTextField1_id.getText();
             try {
            // C:\Users\Shahyar\Desktop
            //JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Report_practise\\report2.jrxml");
              //String sql =  "select * from account";
              JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Inventory_managment\\Reports\\View Customer\\Search_customer.jrxml");

             String sql =  " select * from account where account_id = '"+id+"'";
            
            
            JRDesignQuery  newquer  = new JRDesignQuery();
             newquer.setText(sql);
            jd.setQuery(newquer);
            JasperReport jr =  JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null , con);
             JasperViewer.viewReport(jp,false);
        } catch (JRException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        }
             
             
    }               
    }//GEN-LAST:event_jButton1_search_Customer_printActionPerformed

    private void jTextField1_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_idKeyPressed
       int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField1_id.setEditable(true);
          jTextField1_id.setBackground(Color.yellow);
            jLabel3_status.setText("");
        }
        else
        {
           jTextField1_id.setEditable(false);
             jTextField1_id.setBackground(Color.RED);
           jLabel3_status.setForeground(Color.red);
            jLabel3_status.setText("Please Enter Only Numeric Value");
        }        // TODO add your handling code here:
    
         // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Print_all_Record;
    private javax.swing.JButton jButton1_refresh;
    private javax.swing.JButton jButton1_search_Customer_print;
    private javax.swing.JButton jButton2_search;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3_back_grond;
    private javax.swing.JLabel jLabel3_status;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_id;
    // End of variables declaration//GEN-END:variables
}
