package Products;


import Bill.Conform_bill_bal;
import Bill.New_bill_bal;
import Bill.New_bill;
import Customer.Update_account;
import Login.Main_page;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class Add_qnt_new extends javax.swing.JInternalFrame {

    /**
     * Creates new form Add_qnt_new
     */
    DefaultComboBoxModel product_list;
    public Add_qnt_new() {
        initComponents();
        product_list();
        show_produc_info_show();
        
        jTextField_product_name_show.setEnabled(false);
        jTextField_qnaity_in_stock_add.setEnabled(false);
        jTextField_add_quntity_sho.setText("0");
    }

      
    public void product_list()
    {
      Product_bal ob = new Product_bal();
        Vector <String> v;
       
        try {
            v = ob.Product_name();
             product_list= new DefaultComboBoxModel();
             for (String cb:v) {
               
                product_list.addElement(cb);
             //   JOptionPane.showMessageDialog(null,cb.getCustomer_name());
            }
           } catch (SQLException ex) {
            Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           jComboBox_product_list.setModel(product_list);
             jTextField_product_name_show.setText((String) jComboBox_product_list.getSelectedItem());
    }
    
    public void show_produc_info_show()
    {
        New_bill_bal ob  = new New_bill_bal();
        String s; 
        int Product_rate= 0;
        int product_qnt = 0 ;
        int product_total_amnt =0 ;
        // name
        s = (String) jComboBox_product_list.getSelectedItem();
        jTextField_product_name_show.setText(s);
//        
//        // rate
//        
//         try {
//            Product_rate = ob.getProductRate(s);
//         } catch (SQLException ex) {
//             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
//         }         
//        jTextField_rate_show.setText(String.valueOf(Product_rate));
//        
        //for quantity
        try {
            product_qnt = ob.getProductQuntity(s);
         } catch (SQLException ex) {
             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
         }    
        jTextField_qnaity_in_stock_add.setText(String.valueOf(product_qnt));
//         // for total
//        try {
//            product_total_amnt = ob.getProductTotalAmt(s);
//         } catch (SQLException ex) {
//             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
//         }    
//        jLabel_total_show.setText(String.valueOf(product_total_amnt));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField_add_quntity_sho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_product_list = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6_status = new javax.swing.JLabel();
        jTextField_qnaity_in_stock_add = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_product_name_show = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jButton3_search = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Add Product Quantity");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 300, 72, 50));

        jTextField_add_quntity_sho.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_add_quntity_sho.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_add_quntity_sho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_add_quntity_shoFocusGained(evt);
            }
        });
        jTextField_add_quntity_sho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_add_quntity_shoActionPerformed(evt);
            }
        });
        jTextField_add_quntity_sho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_add_quntity_shoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_add_quntity_sho, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 228, 239, 26));

        jLabel2.setForeground(new java.awt.Color(17, 111, 204));
        jLabel2.setText("Add Quantity");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 104, -1));

        jComboBox_product_list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_product_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_product_listItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox_product_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 114, 239, 26));

        jLabel5.setFont(new java.awt.Font("AR BONNIE", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(104, 104, 232));
        jLabel5.setText("Add Product Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, 400, -1));

        jLabel4.setForeground(new java.awt.Color(17, 111, 204));
        jLabel4.setText("Product Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 104, -1));

        jLabel3.setForeground(new java.awt.Color(17, 111, 204));
        jLabel3.setText("Quantity in Stock");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 104, -1));
        getContentPane().add(jLabel6_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 322, 23));

        jTextField_qnaity_in_stock_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_qnaity_in_stock_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        getContentPane().add(jTextField_qnaity_in_stock_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 190, 239, 26));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Close");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 72, 50));

        jLabel1.setForeground(new java.awt.Color(17, 111, 204));
        jLabel1.setText("Select Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 117, 113, -1));

        jTextField_product_name_show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_product_name_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        getContentPane().add(jTextField_product_name_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 152, 239, 26));

        jLabel6.setForeground(new java.awt.Color(17, 111, 204));
        jLabel6.setText("Enter Product ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 84, 130, 20));

        jTextField1_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField1_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_idFocusGained(evt);
            }
        });
        jTextField1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_idActionPerformed(evt);
            }
        });
        jTextField1_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_idKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 76, 239, 26));

        jButton3_search.setBackground(new java.awt.Color(51, 51, 255));
        jButton3_search.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton3_search.setForeground(new java.awt.Color(255, 255, 255));
        jButton3_search.setText("Search By ID");
        jButton3_search.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_searchActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 150, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 60, 270));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Products/add_quantity_resizesd.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 320, 320));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Products/add_qntity_backgroung.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_product_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_product_listItemStateChanged
        show_produc_info_show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_product_listItemStateChanged

    private void jTextField_add_quntity_shoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_add_quntity_shoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_add_quntity_shoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jTextField1_id.setBackground(Color.white);
        if(jTextField_product_name_show.getText().equalsIgnoreCase(""))
{
     JOptionPane.showMessageDialog(null,"Product Info is Not Available" , this.title, 0);
}
else
{
   
            String  check_qunatity = jTextField_add_quntity_sho.getText();
            jTextField_add_quntity_sho.setBackground(null);
            
            if((check_qunatity.equalsIgnoreCase("")) || check_qunatity.equalsIgnoreCase("0")){
             jTextField_add_quntity_sho.setBackground(Color.red);
            jLabel6_status.setForeground(Color.red);
 JOptionPane.showMessageDialog(null,"Please Enter Complete Product Info" ,"Product Updates" , 2);
                  
// jLabel6_status.setText("Please Enter Complete Information");
            }      
            else
         {
              
                 
                 int option = JOptionPane.showConfirmDialog(null, "Do you Want to Add Product Quantity..??", "Add Quantity", JOptionPane.YES_NO_OPTION , 0);
    
                 if(option == 0 )
                  {
        String product_name = jTextField_product_name_show.getText();

        int quantity = Integer.parseInt(jTextField_add_quntity_sho.getText());

        Product_bal add_qnt = new Product_bal();
        try {
            add_qnt.add_product_quantity(product_name, quantity);
        } catch (SQLException ex) {
            Logger.getLogger(Update_product.class.getName()).log(Level.SEVERE, null, ex);
        }

        //jLabel6_status.setText("Quantity Added");
          JOptionPane.showMessageDialog(null,"Product Quantity is Updated Successfully." ,"Add Quantity Successfully" , 1);
       
        jTextField_add_quntity_sho.setText("0");
        show_produc_info_show();
         }
         }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);        // this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_add_quntity_shoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_add_quntity_shoKeyPressed
  int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField_add_quntity_sho.setEditable(true);
           jTextField_add_quntity_sho.setBackground(Color.yellow);
            jLabel6_status.setText("");
        }
        else
        {
           jTextField_add_quntity_sho.setEditable(false);
             jTextField_add_quntity_sho.setBackground(Color.RED);
            jLabel6_status.setForeground(Color.red);
            jLabel6_status.setText("Please Enter Only Numeric Value");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_add_quntity_shoKeyPressed

    private void jTextField_add_quntity_shoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_add_quntity_shoFocusGained
        // TODO add your handling code here:
        jTextField_add_quntity_sho.setBackground(null);
    }//GEN-LAST:event_jTextField_add_quntity_shoFocusGained

    private void jButton3_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_searchActionPerformed

        jLabel6_status.setText("");
        
        if(String.valueOf(jTextField1_id.getText()).equalsIgnoreCase(""))
        {
           
            
            jTextField1_id.setBackground(Color.RED);
            jLabel6_status.setForeground(Color.red);
            //jLabel6_status.setText("Enter ID First");
             JOptionPane.showMessageDialog(this, "Please Enter Product ID First", "Search ID", 2);
        }
        else{
            
        int id =Integer.parseInt(jTextField1_id.getText());
      
        
        PreparedStatement ps = null;
        ResultSet rs = null;
        String Query = "Select product_name , pruduct_quantity from Inventory\n" +
"where\n" +
"product_id = ?";
         try {       
             ps=Main_page.con.prepareStatement(Query);
             ps.setInt(1, id); 
             rs = ps.executeQuery();
             int count = 0;
            while(rs.next())
            {
                
             jTextField_product_name_show.setText(rs.getString("product_name"));
             jTextField_qnaity_in_stock_add.setText(rs.getString("pruduct_quantity"));
            count++;
                }
                
               Product_bal ob = new Product_bal();
            String product_name;
            product_name = ob.get_single_product_name(id);
            jComboBox_product_list.setSelectedItem(product_name);
                if(count == 0)
                {
                    jLabel6_status.setForeground(Color.red);
                    //jLabel6_status.setText("ID NOT FOUND");
                     JOptionPane.showMessageDialog(this, "Please Enter Correct ID", "Search ID", 2);
                }
            
         } catch (SQLException ex) {
             Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
         }
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_searchActionPerformed

    private void jTextField1_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_idFocusGained
jLabel6_status.setText("");
jTextField1_id.setBackground(Color.WHITE);// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idFocusGained

    private void jTextField1_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_idKeyPressed
int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField1_id.setEditable(true);
          jTextField1_id.setBackground(Color.yellow);
            jLabel6_status.setText("");
        }
        else
        {
           jTextField1_id.setEditable(false);
             jTextField1_id.setBackground(Color.RED);
             jLabel6_status.setForeground(Color.red);
             jLabel6_status.setText("Please Enter Only Numeric Value");
        }              // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idKeyPressed

    private void jTextField1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3_search;
    private javax.swing.JComboBox jComboBox_product_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6_status;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField_add_quntity_sho;
    private javax.swing.JTextField jTextField_product_name_show;
    private javax.swing.JTextField jTextField_qnaity_in_stock_add;
    // End of variables declaration//GEN-END:variables
}
