package Products;


import Bill.Conform_bill_bal;
import Bill.New_bill;
import Bill.New_bill_bal;
import Customer.Update_account;
import Login.Main_page;
import Products.Product_bal;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class Delete_product extends javax.swing.JInternalFrame {

    /**
     * Creates new form Delete_product
     */
     DefaultComboBoxModel product_list;
    public Delete_product() {
        initComponents();
        product_list();
        show_produc_info_show();
         jTextField_name_show.setEnabled(false);
        jTextField_quantity_show.setEnabled(false);
        jTextField2_rate_show.setEnabled(false);
        
       
    }
    
    public void product_list()
    {
      Product_bal ob = new Product_bal();
        Vector <String> v;
       
        try {
            v = ob.Product_name();
             product_list= new DefaultComboBoxModel();
             for (String cb:v) {
               
                product_list.addElement(cb);
             //   JOptionPane.showMessageDialog(null,cb.getCustomer_name());
            }
           } catch (SQLException ex) {
            Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           jComboBox1_product_name.setModel(product_list);
             jTextField_name_show.setText((String) jComboBox1_product_name.getSelectedItem());
    }
    
     
    public void show_produc_info_show()
    {
        New_bill_bal ob  = new New_bill_bal();
        String s; 
        int Product_rate= 0;
        int product_qnt = 0 ;
        int product_total_amnt =0 ;
        // name
        s = (String) jComboBox1_product_name.getSelectedItem();
        jTextField_name_show.setText(s);
        
        // rate
        
         try {
            Product_rate = ob.getProductRate(s);
         } catch (SQLException ex) {
             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
         }         
        jTextField2_rate_show.setText(String.valueOf(Product_rate));
        
        //for quantity
        try {
            product_qnt = ob.getProductQuntity(s);
         } catch (SQLException ex) {
             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
         }    
        jTextField_quantity_show.setText(String.valueOf(product_qnt));
//         // for total
//        try {
//            product_total_amnt = ob.getProductTotalAmt(s);
//         } catch (SQLException ex) {
//             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
//         }    
//        jLabel_total_show.setText(String.valueOf(product_total_amnt));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1_product_name = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField_name_show = new javax.swing.JTextField();
        jTextField2_rate_show = new javax.swing.JTextField();
        jTextField_quantity_show = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1_dlt = new javax.swing.JButton();
        jLabel6_status = new javax.swing.JLabel();
        jButton2close = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_id = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jlabel_background = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Delete Product");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(17, 111, 204));
        jLabel1.setText("Select Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 104, -1, -1));

        jLabel2.setForeground(new java.awt.Color(17, 111, 204));
        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 142, -1, -1));

        jComboBox1_product_name.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1_product_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1_product_nameItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 101, 196, 26));

        jLabel3.setForeground(new java.awt.Color(17, 111, 204));
        jLabel3.setText("Rate");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 177, 63, -1));

        jTextField_name_show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_name_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_name_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_name_showActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_name_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 139, 196, 26));

        jTextField2_rate_show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2_rate_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField2_rate_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_rate_showActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2_rate_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 174, 196, 26));

        jTextField_quantity_show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_quantity_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_quantity_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_quantity_showActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_quantity_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 205, 196, 26));

        jLabel5.setFont(new java.awt.Font("AR BONNIE", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(104, 104, 232));
        jLabel5.setText("Delete Product");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, 228, 36));

        jLabel4.setForeground(new java.awt.Color(17, 111, 204));
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 205, -1, -1));

        jButton1_dlt.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_dlt.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1_dlt.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_dlt.setText("Delete");
        jButton1_dlt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1_dlt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_dltActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_dlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 60, 40));
        getContentPane().add(jLabel6_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 231, 277, 23));

        jButton2close.setBackground(new java.awt.Color(51, 51, 255));
        jButton2close.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton2close.setForeground(new java.awt.Color(255, 255, 255));
        jButton2close.setText("Close");
        jButton2close.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2closeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2close, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 60, 40));

        jLabel6.setForeground(new java.awt.Color(17, 111, 204));
        jLabel6.setText("Enter Product ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 73, 99, -1));

        jTextField1_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField1_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_idFocusGained(evt);
            }
        });
        jTextField1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_idActionPerformed(evt);
            }
        });
        jTextField1_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_idKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 70, 196, 26));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 50, 240));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search By ID");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Products/Garbage.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 250, 290));

        jlabel_background.setFont(new java.awt.Font("AR BERKLEY", 0, 18)); // NOI18N
        jlabel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Products/Delete_product_background.jpg"))); // NOI18N
        getContentPane().add(jlabel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1_product_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1_product_nameItemStateChanged
        // TODO add your handling code here:
        show_produc_info_show();
    }//GEN-LAST:event_jComboBox1_product_nameItemStateChanged

    private void jButton1_dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_dltActionPerformed
if(jTextField_name_show.getText().equals(""))
{
   // jLabel6_status.setText("Customer Info Not Available");
    JOptionPane.showMessageDialog(null,"Product Info is Not Available" ,"Delete" , 0);
}
else
{
    int option = JOptionPane.showConfirmDialog(null, "Do you Want to delete..??", "Delete", JOptionPane.YES_NO_OPTION , 0);
    
    if(option== 0 )
    {  
       String product_name = jTextField_name_show.getText();
      
       
       Product_bal delete_product = new Product_bal();
        try {
            delete_product.Delete_product(product_name);
        } catch (SQLException ex) {
            Logger.getLogger(Update_product.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
         JOptionPane.showMessageDialog(null,"Product Deleted" ,"Delete" , 2);
        //jLabel6_status.setText("Product Deleted");
         product_list();
         show_produc_info_show();
         jTextField1_id.setText("");
        }
}

    }//GEN-LAST:event_jButton1_dltActionPerformed

    private void jButton2closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2closeActionPerformed

    private void jTextField_quantity_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_quantity_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_quantity_showActionPerformed

    private void jTextField1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabel6_status.setText("");

        if(String.valueOf(jTextField1_id.getText()).equalsIgnoreCase(""))
        {

            jTextField1_id.setBackground(Color.RED);
            jLabel6_status.setForeground(Color.red);
            //jLabel6_status.setText("Enter ID First");
             JOptionPane.showMessageDialog(this, "Please Enter Product ID First", "Search ID", 2);
        }
        else{

            int id =Integer.parseInt(jTextField1_id.getText());

            PreparedStatement ps = null;
            ResultSet rs = null;
            String Query = "Select product_name , pruduct_quantity  , pruduct_rate from Inventory\n" +
    "where\n" +
    "product_id = ?";
            try {
                ps=Main_page.con.prepareStatement(Query);
                ps.setInt(1, id);
                rs = ps.executeQuery();
                int count = 0;
                while(rs.next())
                {

                    jTextField_name_show.setText(rs.getString("product_name"));
                    jTextField_quantity_show.setText(rs.getString("pruduct_quantity"));
                    jTextField2_rate_show.setText(rs.getString("pruduct_rate"));
                    
                    count++;
                }
            Product_bal ob = new Product_bal();
            String customer_name;
            customer_name = ob.get_single_product_name(id);
            jComboBox1_product_name.setSelectedItem(customer_name);
                if(count == 0)
                {
                    jLabel6_status.setForeground(Color.red);
                 //   jLabel6_status.setText("ID NOT FOUND");
                    JOptionPane.showMessageDialog(this, "Please Enter Correct ID", "Search ID", 2);
                }

            } catch (SQLException ex) {
                Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_idFocusGained
        jLabel6_status.setText("");
        jTextField1_id.setBackground(Color.white);
    }//GEN-LAST:event_jTextField1_idFocusGained

    private void jTextField1_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_idKeyPressed
   int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField1_id.setEditable(true);
          jTextField1_id.setBackground(Color.yellow);
            jLabel6_status.setText("");
        }
        else
        {
           jTextField1_id.setEditable(false);
             jTextField1_id.setBackground(Color.RED);
             jLabel6_status.setForeground(Color.red);
             jLabel6_status.setText("Please Enter Only Numeric Value");
        }               // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idKeyPressed

    private void jTextField_name_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_name_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_name_showActionPerformed

    private void jTextField2_rate_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_rate_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_rate_showActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_dlt;
    private javax.swing.JButton jButton2close;
    private javax.swing.JComboBox jComboBox1_product_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6_status;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1_id;
    private javax.swing.JTextField jTextField2_rate_show;
    private javax.swing.JTextField jTextField_name_show;
    private javax.swing.JTextField jTextField_quantity_show;
    private javax.swing.JLabel jlabel_background;
    // End of variables declaration//GEN-END:variables
}
