package Products;


import Bill.Conform_bill_bal;
import Bill.New_bill;
import Bill.New_bill_bal;
import Customer.Account_bal;
import Customer.Update_account;
import Login.Main_page;
import Products.Product_bal;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class Update_product extends javax.swing.JInternalFrame {

    /**
     * Creates new form Update_product
     */
    DefaultComboBoxModel product_list;
    public Update_product() {
        initComponents();
        product_list();
        show_produc_info_show();
        jtextfield_product_name_show.setEnabled(false);
        jTextField_product_qnt_show.setEnabled(false);
        jTextField_rate_show.setEnabled(false);
        jTextField_enter_new_rate.setText("0");
        jTextField_enter_new_quantity.setText("0");
        jTextField_New_product_name.setEnabled(false);
        jCheckBox_changeProduct_name.setBackground(null);
    }
    
    
    public void product_list()
    {
      Product_bal ob = new Product_bal();
        Vector <String> v;
       
        try {
            v = ob.Product_name();
             product_list= new DefaultComboBoxModel();
             for (String cb:v) {
               
                product_list.addElement(cb);
             //   JOptionPane.showMessageDialog(null,cb.getCustomer_name());
            }
           } catch (SQLException ex) {
            Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           jComboBox_product_list.setModel(product_list);
             jtextfield_product_name_show.setText((String) jComboBox_product_list.getSelectedItem());
    }
    
    
    
    
    
    public void show_produc_info_show()
    {
        New_bill_bal ob  = new New_bill_bal();
        String s; 
        int Product_rate= 0;
        int product_qnt = 0 ;
        int product_total_amnt =0 ;
        // name
        s = (String) jComboBox_product_list.getSelectedItem();
        jtextfield_product_name_show.setText(s);
        
        // rate
        
         try {
            Product_rate = ob.getProductRate(s);
         } catch (SQLException ex) {
             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
         }         
        jTextField_rate_show.setText(String.valueOf(Product_rate));
        
        //for quantity
        try {
            product_qnt = ob.getProductQuntity(s);
         } catch (SQLException ex) {
             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
         }    
        jTextField_product_qnt_show.setText(String.valueOf(product_qnt));
//         // for total
//        try {
//            product_total_amnt = ob.getProductTotalAmt(s);
//         } catch (SQLException ex) {
//             Logger.getLogger(New_bill.class.getName()).log(Level.SEVERE, null, ex);
//         }    
//        jLabel_total_show.setText(String.valueOf(product_total_amnt));
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_product_list = new javax.swing.JComboBox();
        jtextfield_product_name_show = new javax.swing.JTextField();
        jTextField_product_qnt_show = new javax.swing.JTextField();
        jTextField_rate_show = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_enter_new_quantity = new javax.swing.JTextField();
        jTextField_enter_new_rate = new javax.swing.JTextField();
        jButton_update = new javax.swing.JButton();
        jButton_close = new javax.swing.JButton();
        jLabel_status = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_New_product_name = new javax.swing.JTextField();
        jCheckBox_changeProduct_name = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField1_product_id = new javax.swing.JTextField();
        jButton1_search_id = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Update Product");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AR BONNIE", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 104, 232));
        jLabel1.setText("Update Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, 230, 52));

        jLabel2.setForeground(new java.awt.Color(17, 111, 204));
        jLabel2.setText("Select Product");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 115, -1, -1));

        jLabel3.setForeground(new java.awt.Color(17, 111, 204));
        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 154, -1, -1));

        jLabel4.setForeground(new java.awt.Color(17, 111, 204));
        jLabel4.setText("Old Product Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 194, -1, -1));

        jLabel5.setForeground(new java.awt.Color(17, 111, 204));
        jLabel5.setText("Old Product Rate");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 232, -1, -1));

        jComboBox_product_list.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_product_list.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_product_listItemStateChanged(evt);
            }
        });
        jComboBox_product_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_product_listActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_product_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 112, 144, -1));

        jtextfield_product_name_show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtextfield_product_name_show.setText("Product Name");
        jtextfield_product_name_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jtextfield_product_name_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextfield_product_name_showActionPerformed(evt);
            }
        });
        getContentPane().add(jtextfield_product_name_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 151, 144, 26));

        jTextField_product_qnt_show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_product_qnt_show.setText("0");
        jTextField_product_qnt_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_product_qnt_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_product_qnt_showActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_product_qnt_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 191, 144, 26));

        jTextField_rate_show.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_rate_show.setText("0");
        jTextField_rate_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        getContentPane().add(jTextField_rate_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 229, 144, 26));

        jLabel6.setForeground(new java.awt.Color(17, 111, 204));
        jLabel6.setText("Enter New Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 194, -1, -1));

        jLabel7.setForeground(new java.awt.Color(17, 111, 204));
        jLabel7.setText("Enter New Rate");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 232, 95, -1));

        jTextField_enter_new_quantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_enter_new_quantity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_enter_new_quantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_enter_new_quantityFocusGained(evt);
            }
        });
        jTextField_enter_new_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_enter_new_quantityKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_enter_new_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 191, 93, 26));

        jTextField_enter_new_rate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_enter_new_rate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_enter_new_rate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_enter_new_rateFocusGained(evt);
            }
        });
        jTextField_enter_new_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_enter_new_rateActionPerformed(evt);
            }
        });
        jTextField_enter_new_rate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_enter_new_rateKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField_enter_new_rate, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 229, 93, 26));

        jButton_update.setBackground(new java.awt.Color(51, 51, 255));
        jButton_update.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update.setText("Update");
        jButton_update.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 291, 81, 59));

        jButton_close.setBackground(new java.awt.Color(51, 51, 255));
        jButton_close.setForeground(new java.awt.Color(255, 255, 255));
        jButton_close.setText("Close");
        jButton_close.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 81, 59));
        getContentPane().add(jLabel_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 267, 233, 23));

        jLabel8.setForeground(new java.awt.Color(17, 111, 204));
        jLabel8.setText("Enter New Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 115, 95, -1));

        jTextField_New_product_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField_New_product_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField_New_product_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_New_product_nameFocusGained(evt);
            }
        });
        getContentPane().add(jTextField_New_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 112, 93, 26));

        jCheckBox_changeProduct_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox_changeProduct_name.setForeground(new java.awt.Color(11, 75, 139));
        jCheckBox_changeProduct_name.setText("Change Name");
        jCheckBox_changeProduct_name.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox_changeProduct_nameItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox_changeProduct_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 150, -1, -1));

        jLabel9.setForeground(new java.awt.Color(17, 111, 204));
        jLabel9.setText("Enter Product ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 77, 101, -1));

        jTextField1_product_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1_product_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(40, 40, 126), 2, true));
        jTextField1_product_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_product_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1_product_idFocusLost(evt);
            }
        });
        jTextField1_product_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_product_idKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 74, 144, 26));

        jButton1_search_id.setBackground(new java.awt.Color(51, 51, 255));
        jButton1_search_id.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_search_id.setText("Search By ID");
        jButton1_search_id.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1_search_id.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_search_idActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_search_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 90, 59));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 20, 230));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Products/Update_product_background.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closeActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_closeActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
if(jtextfield_product_name_show.getText().equalsIgnoreCase(""))
{
     JOptionPane.showMessageDialog(null,"Product Info is Not Available" ,"Delete" , 0);
}
else
{
    
       Product_bal update_product = new Product_bal();
       String product_name = jtextfield_product_name_show.getText();        
       String  check_qunatity = jTextField_enter_new_quantity.getText();
       String  check_rate = jTextField_enter_new_rate.getText();
       jTextField_enter_new_quantity.setBackground(null);
       jTextField_enter_new_rate.setBackground(null);
        
        if(jCheckBox_changeProduct_name.isSelected())
        { 
            
        String update_product_name = jTextField_New_product_name.getText();
        
            if(update_product_name.equalsIgnoreCase("")|| (check_qunatity.equalsIgnoreCase("")) || (check_qunatity.equalsIgnoreCase("0")) ||(check_rate.equalsIgnoreCase("")) ||(check_rate.equalsIgnoreCase("0")))
            {
                
                if( (check_qunatity.equalsIgnoreCase("") ||check_qunatity.equalsIgnoreCase("0")) && (check_rate.equalsIgnoreCase("") || check_rate.equalsIgnoreCase("0")) && update_product_name.equalsIgnoreCase(""))
                {
                    jTextField_enter_new_quantity.setBackground(Color.red);
                    jLabel_status.setForeground(Color.red);
                     jTextField_enter_new_rate.setBackground(Color.red);
                     jLabel_status.setForeground(Color.red);
                    jTextField_New_product_name.setBackground(Color.red);
                    jLabel_status.setForeground(Color.red);
                    JOptionPane.showMessageDialog(null,"Please Enter Complete Product Info" ,"Product Updates" , 2);
                
                }
                else
                {
            
                                if(check_qunatity.equalsIgnoreCase("") ||check_qunatity.equalsIgnoreCase("0"))
                            {
                                                jTextField_enter_new_quantity.setBackground(Color.red);
                                                jLabel_status.setForeground(Color.red);
                                               // jLabel_status.setText("Please Enter Complete Information");
                                               JOptionPane.showMessageDialog(null,"Please Enter Product Quantity" ,"Product Quantity Alert" , 1);
                     
                            }


                                if(check_rate.equalsIgnoreCase("") || check_rate.equalsIgnoreCase("0"))
                            {
                                                jTextField_enter_new_rate.setBackground(Color.red);
                                                jLabel_status.setForeground(Color.red);
                                               // jLabel_status.setText("Please Enter Complete Information");
                                            JOptionPane.showMessageDialog(null,"Please Enter Product Rate" ,"Product Rate Alert" , 1);
                     
                            
                            }

                                if(update_product_name.equalsIgnoreCase(""))
                                {
                                    jTextField_New_product_name.setBackground(Color.red);
                                    jLabel_status.setForeground(Color.red);
                                    //jLabel_status.setText("Please Enter Complete Information");
                                   JOptionPane.showMessageDialog(null,"Please Enter Product Name" ,"Product Name Alert" , 1);
                     
                         
                                }
                }
            }                          
                        else
                        {
                 int option = JOptionPane.showConfirmDialog(null, "Do you Want to Update..??", "Update", JOptionPane.YES_NO_OPTION , 0);
    
                 if(option == 0 )
                  {
                     int rate = Integer.parseInt(jTextField_enter_new_rate.getText());
                     int quantity = Integer.parseInt(jTextField_enter_new_quantity.getText());

                    try {
                        update_product.update_product_quantity(product_name, quantity);
                    } catch (SQLException ex) {
                        Logger.getLogger(Update_product.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        update_product.update_product_rate(product_name, rate);
                    } catch (SQLException ex) {
                        Logger.getLogger(Update_product.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
                    try {
                        update_product.update_product_Name(update_product_name, product_name);
                    } catch (SQLException ex) {
                        Logger.getLogger(Update_product.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                 //jLabel_status.setText("Product Updated");
                     JOptionPane.showMessageDialog(null,"Product Is Successfully Updated." ,"Product Update" , 0);
                     jTextField_New_product_name.setText("");
                     jTextField_enter_new_quantity.setText("0");
                     jTextField_enter_new_rate.setText("0");
                 product_list();
                 show_produc_info_show();          
                        }
                        }
                // iiner else for conditon when checbox is selected
            }
                else
                {
                 
                    
                     if((check_qunatity.equalsIgnoreCase("")) || (check_qunatity.equalsIgnoreCase("0")) ||(check_rate.equalsIgnoreCase("")) ||(check_rate.equalsIgnoreCase("0")))
                            {
                
                if((check_qunatity.equalsIgnoreCase("") ||check_qunatity.equalsIgnoreCase("0")) && (check_rate.equalsIgnoreCase("") || check_rate.equalsIgnoreCase("0")))
                {
                      jTextField_enter_new_quantity.setBackground(Color.red);
                      jTextField_enter_new_rate.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null,"Please Enter Complete Product Info" ,"Product Updates" , 2);                           
                }
                else
                {
            
                                     if(check_qunatity.equalsIgnoreCase("") ||check_qunatity.equalsIgnoreCase("0"))
                                        {
                                                jTextField_enter_new_quantity.setBackground(Color.red);
                                                jLabel_status.setForeground(Color.red);
                                                 JOptionPane.showMessageDialog(null,"Please Enter Product Quantity" ,"Product Quantity Alert" , 1);
                     
                                              //  jLabel_status.setText("Please Enter Complete Information");
                                        }
                

                                    if(check_rate.equalsIgnoreCase("") || check_rate.equalsIgnoreCase("0"))
                                        {
                                                jTextField_enter_new_rate.setBackground(Color.red);
                                                jLabel_status.setForeground(Color.red);
                                             JOptionPane.showMessageDialog(null,"Please Enter Product Rate" ,"Product Rate Alert" , 1);
                        
                                               // jLabel_status.setText("Please Enter Complete Information");
                                        }
                                    
                }
                            }
                    else
                        {
                            int option = JOptionPane.showConfirmDialog(null, "Do you Want to Update..??", "Update", JOptionPane.YES_NO_OPTION , 0);
    
                 if(option == 0 )
                  {
                                    int rate = Integer.parseInt(jTextField_enter_new_rate.getText());
                                    int quantity = Integer.parseInt(jTextField_enter_new_quantity.getText());

                                try {
                                    update_product.update_product_quantity(product_name, quantity);
                                    } catch (SQLException ex) {
                                    Logger.getLogger(Update_product.class.getName()).log(Level.SEVERE, null, ex);
                                                              }
                                try {
                                      update_product.update_product_rate(product_name, rate);
                                      } catch (SQLException ex) {
                                    Logger.getLogger(Update_product.class.getName()).log(Level.SEVERE, null, ex);
                                                                } 
                    
                               //jLabel_status.setText("Product Updated");
                                 JOptionPane.showMessageDialog(null,"Product Is Successfully Updated." ,"Product Update" , 0);
                                    jTextField_New_product_name.setText("");
                                    jTextField_enter_new_quantity.setText("0");
                                    jTextField_enter_new_rate.setText("0");
                               product_list();
                               show_produc_info_show();                           
                        }// inner else
                }
                        

                        } // oter else
       
       
                // when check box is not selected
        
}// when field have some value

    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jComboBox_product_listItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_product_listItemStateChanged
       show_produc_info_show();
       jButton_update.setEnabled(true);
       jTextField_enter_new_quantity.setBackground(Color.WHITE);
          jTextField_enter_new_rate.setBackground(Color.WHITE);
          jTextField_New_product_name.setBackground(Color.WHITE);
          jTextField1_product_id.setBackground(Color.WHITE);
          
         jTextField_New_product_name.setText("");
         jTextField_enter_new_quantity.setText("0");
         jTextField_enter_new_rate.setText("0");
    }//GEN-LAST:event_jComboBox_product_listItemStateChanged

    private void jTextField_enter_new_quantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_enter_new_quantityKeyPressed
 int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField_enter_new_quantity.setEditable(true);
          jTextField_enter_new_quantity.setBackground(Color.yellow);
            jLabel_status.setText("");
        }
        else
        {
           jTextField_enter_new_quantity.setEditable(false);
             jTextField_enter_new_quantity.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
            jLabel_status.setText("Please Enter Only Numeric Value");
        }        // TODO add your handling code here:
    
        
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField_enter_new_quantityKeyPressed

    private void jTextField_enter_new_rateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_enter_new_rateKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField_enter_new_rate.setEditable(true);
          jTextField_enter_new_rate.setBackground(Color.yellow);
            jLabel_status.setText("");
        }
        else
        {
           jTextField_enter_new_rate.setEditable(false);
             jTextField_enter_new_rate.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
            jLabel_status.setText("Please Enter Only Numeric Value");
        }        // TODO add your hand
    }//GEN-LAST:event_jTextField_enter_new_rateKeyPressed

    private void jTextField_enter_new_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_enter_new_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_enter_new_rateActionPerformed

    private void jCheckBox_changeProduct_nameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox_changeProduct_nameItemStateChanged
       
        if(jCheckBox_changeProduct_name.isSelected())
        {
            jTextField_New_product_name.setEnabled(true);
        }
        if(jCheckBox_changeProduct_name.isSelected() == false)
        {
            jTextField_New_product_name.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBox_changeProduct_nameItemStateChanged

    private void jTextField_enter_new_rateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_enter_new_rateFocusGained
       jTextField_enter_new_rate.setBackground(Color.WHITE);
       jLabel_status.setText("");
    }//GEN-LAST:event_jTextField_enter_new_rateFocusGained

    private void jTextField_enter_new_quantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_enter_new_quantityFocusGained
        // TODO add your handling code here:
          jTextField_enter_new_quantity.setBackground(Color.WHITE);
       jLabel_status.setText("");
    }//GEN-LAST:event_jTextField_enter_new_quantityFocusGained

    private void jTextField_New_product_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_New_product_nameFocusGained
        // TODO add your handling code here:
         jTextField_New_product_name.setBackground(Color.WHITE);
          
       jLabel_status.setText("");
    }//GEN-LAST:event_jTextField_New_product_nameFocusGained

    private void jButton1_search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_search_idActionPerformed
 
        jLabel_status.setText("");
        
        if(String.valueOf(jTextField1_product_id.getText()).equalsIgnoreCase(""))
        {
            
            
            jTextField1_product_id.setBackground(Color.RED);
            jLabel_status.setForeground(Color.red);
              JOptionPane.showMessageDialog(this, "Please Enter Product ID First", "Search ID", 2);
           // jLabel_status.setText("Enter ID First");
        }
        else{
        
        int id = Integer.parseInt(jTextField1_product_id.getText());
       PreparedStatement ps = null;
            ResultSet rs = null;
            String Query = "Select product_name , pruduct_quantity  , pruduct_rate from Inventory\n" +
    "where\n" +
    "product_id = ?";
            try {
                ps=Main_page.con.prepareStatement(Query);
                ps.setInt(1, id);
                rs = ps.executeQuery();
                int count = 0;
                while(rs.next())
                {

                    jtextfield_product_name_show.setText(rs.getString("product_name"));
                    jTextField_product_qnt_show.setText(rs.getString("pruduct_quantity"));
                    jTextField_rate_show.setText(rs.getString("pruduct_rate"));
                    jButton_update.setEnabled(true);
                    count++;
            }
            
            Product_bal ob = new Product_bal();
            String product_name;
            product_name = ob.get_single_product_name(id);
            jComboBox_product_list.setSelectedItem(product_name);
                if(count == 0)
                {
                    jLabel_status.setForeground(Color.red);
                 //   jLabel_status.setText("ID NOT FOUND");
                      JOptionPane.showMessageDialog(this, "Please Enter Correct ID", "Search ID", 2);
                    jButton_update.setEnabled(false);
                }
            
            
         } catch (SQLException ex) {
             Logger.getLogger(Update_account.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        }   
        jTextField_New_product_name.setText("");
jTextField_enter_new_rate.setText("");
jTextField_enter_new_quantity.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1_search_idActionPerformed

    private void jTextField1_product_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_product_idFocusGained
        // TODO add your handling code here:
        jTextField1_product_id.setBackground(Color.WHITE);
         jTextField_enter_new_rate.setBackground(Color.WHITE);
         jLabel_status.setText("");
       jTextField_enter_new_quantity.setBackground(Color.WHITE);
          jTextField_enter_new_rate.setBackground(Color.WHITE);
          jTextField_New_product_name.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField1_product_idFocusGained

    private void jTextField1_product_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_product_idFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_product_idFocusLost

    private void jtextfield_product_name_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextfield_product_name_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextfield_product_name_showActionPerformed

    private void jTextField_product_qnt_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_product_qnt_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_product_qnt_showActionPerformed

    private void jTextField1_product_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_product_idKeyPressed
         int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField1_product_id.setEditable(true);
          jTextField1_product_id.setBackground(Color.yellow);
            jLabel_status.setText("");
        }
        else
        {
           jTextField1_product_id.setEditable(false);
             jTextField1_product_id.setBackground(Color.RED);
           jLabel_status.setForeground(Color.red);
            jLabel_status.setText("Please Enter Only Numeric Value");
        }        // TODO add your handling code here:
    
    }//GEN-LAST:event_jTextField1_product_idKeyPressed

    private void jComboBox_product_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_product_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_product_listActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_search_id;
    private javax.swing.JButton jButton_close;
    private javax.swing.JButton jButton_update;
    private javax.swing.JCheckBox jCheckBox_changeProduct_name;
    private javax.swing.JComboBox jComboBox_product_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_status;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1_product_id;
    private javax.swing.JTextField jTextField_New_product_name;
    private javax.swing.JTextField jTextField_enter_new_quantity;
    private javax.swing.JTextField jTextField_enter_new_rate;
    private javax.swing.JTextField jTextField_product_qnt_show;
    private javax.swing.JTextField jTextField_rate_show;
    private javax.swing.JTextField jtextfield_product_name_show;
    // End of variables declaration//GEN-END:variables
}
