package Products;

import Data_base_Conection.DataBase_connection;
import Login.Main_page;
import static Login.Main_page.con;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahyar
 */
public class View_product extends javax.swing.JInternalFrame {

    /**
     * Creates new form View_product
     */
    
    public View_product() throws SQLException {
        initComponents();
        
        PreparedStatement ps =null;
        ResultSet rs=null;
       /// Vector <String> a = new Vector<>();
        String Query="select * from Inventory";
        ps=Main_page.con.prepareStatement(Query);
        rs=ps.executeQuery();
        
        
        ResultSetMetaData rsmetadata = rs.getMetaData();
        int columbs = rsmetadata.getColumnCount();
        DefaultTableModel dtm  = new DefaultTableModel();
       Vector colums_name = new Vector();
        Vector datarows = new Vector();
        for(int  i = 1 ; i <= columbs ; i++){
            colums_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(colums_name);       
        while(rs.next())
        {
           datarows = new Vector();
           for(int j = 1 ; j <=columbs ; j++)
           {
               datarows.addElement(rs.getString(j));
           }
           dtm.addRow(datarows);
           
        }
        jTable1.setModel(dtm);
       
       
        
        jButton_srch_record.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_All_product_record = new javax.swing.JButton();
        jButton_srch_record = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3_status = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1_id = new javax.swing.JTextField();
        jButton2_search_product = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1_reh = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 51, 51));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setIconifiable(true);
        setTitle("Product List");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_All_product_record.setBackground(new java.awt.Color(255, 102, 0));
        jButton_All_product_record.setText("Print All Redords");
        jButton_All_product_record.setToolTipText("Print All Records");
        jButton_All_product_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_All_product_recordActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_All_product_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 479, 120, 50));

        jButton_srch_record.setBackground(new java.awt.Color(255, 102, 0));
        jButton_srch_record.setText("Print Search Records");
        jButton_srch_record.setToolTipText("Print Search Records");
        jButton_srch_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_srch_recordActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_srch_record, new org.netbeans.lib.awtextra.AbsoluteConstraints(918, 479, -1, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Enter Product ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 125, 20));
        getContentPane().add(jLabel3_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 132, 354, 26));

        jTable1.setBackground(new java.awt.Color(0, 153, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setToolTipText("Show Product Records");
        jTable1.setGridColor(new java.awt.Color(255, 153, 0));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1195, 330));

        jTextField1_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1_idFocusGained(evt);
            }
        });
        jTextField1_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_idActionPerformed(evt);
            }
        });
        jTextField1_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1_idKeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 156, -1));

        jButton2_search_product.setBackground(new java.awt.Color(255, 102, 0));
        jButton2_search_product.setText("Search Product");
        jButton2_search_product.setToolTipText("Search Product");
        jButton2_search_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_search_productActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2_search_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 120, 30));

        jLabel4.setFont(new java.awt.Font("AR BONNIE", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("All available products");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, 330, 52));

        jButton1_reh.setBackground(new java.awt.Color(255, 102, 0));
        jButton1_reh.setText("Refresh Records");
        jButton1_reh.setToolTipText("Refresh");
        jButton1_reh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_rehActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_reh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Products/technology-background-visual-effect-1920x1080.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_rehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_rehActionPerformed
    
        
        PreparedStatement ps =null;
        ResultSet rs=null;
       /// Vector <String> a = new Vector<>();
        String Query="select * from Inventory";
        try {
            
            
            
            ps=Main_page.con.prepareStatement(Query);
       
        rs=ps.executeQuery();
        
        ResultSetMetaData rsmetadata = rs.getMetaData();
        int columbs = rsmetadata.getColumnCount();
        DefaultTableModel dtm  = new DefaultTableModel();
       Vector colums_name = new Vector();
        Vector datarows = new Vector();
        for(int  i = 1 ; i <= columbs ; i++){
            colums_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(colums_name);       
        while(rs.next())
        {
           datarows = new Vector();
           for(int j = 1 ; j <=columbs ; j++)
           {
               datarows.addElement(rs.getString(j));
           }
           dtm.addRow(datarows);
           
        }
        jTable1.setModel(dtm);
      } catch (SQLException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jLabel3_status.setText("");
        jTextField1_id.setBackground(Color.WHITE);
        jButton_srch_record.setEnabled(false);
    }//GEN-LAST:event_jButton1_rehActionPerformed

    private void jButton2_search_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_search_productActionPerformed
           jLabel3_status.setText("");

        if(String.valueOf(jTextField1_id.getText()).equalsIgnoreCase(""))
        {

            jTextField1_id.setBackground(Color.RED);
            jLabel3_status.setForeground(Color.red);
  JOptionPane.showMessageDialog(this, "Please Enter Product ID First", "Search ID", 2);            
//jLabel3_status.setText("Enter Product ID First");
        }
        else{
        
     
        int id = Integer.parseInt(jTextField1_id.getText());
        PreparedStatement ps =null;
        ResultSet rs=null;
       /// Vector <String> a = new Vector<>();
        String Query="select * from Inventory \n" +
       "where \n" +
        "product_id = ?";
        try {
            
            
            
            ps=Main_page.con.prepareStatement(Query);
             ps.setInt(1, id);    
           rs=ps.executeQuery();
        
        ResultSetMetaData rsmetadata = rs.getMetaData();
        int columbs = rsmetadata.getColumnCount();
        DefaultTableModel dtm  = new DefaultTableModel();
       Vector colums_name = new Vector();
        Vector datarows = new Vector();
        for(int  i = 1 ; i <= columbs ; i++){
            colums_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(colums_name);       
        while(rs.next())
        {
           datarows = new Vector();
           for(int j = 1 ; j <=columbs ; j++)
           {
               datarows.addElement(rs.getString(j));
           }
           dtm.addRow(datarows);
           
        }
        jTable1.setModel(dtm);
        jButton_srch_record.setEnabled(true);
      } catch (SQLException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }
        
        
    }//GEN-LAST:event_jButton2_search_productActionPerformed

    private void jTextField1_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1_idFocusGained
        // TODO add your handling code here:
        jTextField1_id.setBackground(Color.WHITE);
        jLabel3_status.setText("");
    }//GEN-LAST:event_jTextField1_idFocusGained

    private void jButton_All_product_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_All_product_recordActionPerformed
            
        try {
            // C:\Users\Shahyar\Desktop
            //JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Report_practise\\report2.jrxml");
              //String sql =  "select * from account";
              JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Inventory_managment\\Reports\\View Products\\View_All_Products.jrxml");

             String sql =  "select * from Inventory";
            
            
            JRDesignQuery  newquer  = new JRDesignQuery();
             newquer.setText(sql);
            jd.setQuery(newquer);
            JasperReport jr =  JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null , con);
             JasperViewer.viewReport(jp,false);
        } catch (JRException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_All_product_recordActionPerformed

    private void jButton_srch_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_srch_recordActionPerformed
        
        if(jTable1.getRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this,"No Record Available");
        }
        else
        {
            String  id = jTextField1_id.getText();
             try {
            // C:\Users\Shahyar\Desktop
            //JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Report_practise\\report2.jrxml");
              //String sql =  "select * from account";
              JasperDesign jd  = JRXmlLoader.load("C:\\Users\\Shahyar\\Documents\\NetBeansProjects\\Inventory_managment\\Reports\\View Products\\Search_Product_report.jrxml");

             String sql =  "select * from Inventory  where  product_id = '"+id+"'  ";
            
            
            JRDesignQuery  newquer  = new JRDesignQuery();
             newquer.setText(sql);
            jd.setQuery(newquer);
            JasperReport jr =  JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null , con);
             JasperViewer.viewReport(jp,false);
        } catch (JRException ex) {
            Logger.getLogger(View_product.class.getName()).log(Level.SEVERE, null, ex);
        }
             
             
    }               
        
    }//GEN-LAST:event_jButton_srch_recordActionPerformed

    private void jTextField1_idKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_idKeyPressed
        int key = evt.getKeyCode();
        if((key >= evt.VK_0&&key<=evt.VK_9) || (key>=evt.VK_NUMPAD0 && key<= evt.VK_NUMPAD9) || key==KeyEvent.VK_BACKSPACE)
        {
             jTextField1_id.setEditable(true);
          jTextField1_id.setBackground(Color.yellow);
            jLabel3_status.setText("");
        }
        else
        {
           jTextField1_id.setEditable(false);
             jTextField1_id.setBackground(Color.RED);
             jLabel3_status.setForeground(Color.red);
             jLabel3_status.setText("Please Enter Only Numeric Value");
        }        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_jTextField1_idKeyPressed

    private void jTextField1_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_reh;
    private javax.swing.JButton jButton2_search_product;
    private javax.swing.JButton jButton_All_product_record;
    private javax.swing.JButton jButton_srch_record;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3_status;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_id;
    // End of variables declaration//GEN-END:variables
}
